### ISSUE TITLE
Hagamos una charla de 15 minutos en inglés en cada meetup 😱

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#1]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [X] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

La falta de bilingüismo es para muchas personas una barrera al momento de alcanzar nuevas metas. Nuestra comunidad tal vez no tenga la capacidad de resolver este problema, pero seguramente puede poner su granito de arena. 

Así que propongo que durante cada meetup saquemos un espacio de 15 minutos **(tan solo 15 minutos)** en los que un speaker dé una charla en inglés. Tal vez no entendamos nada o muy poco, pero será una excelente manera de incentivarnos a la práctica del inglés.

(👍 if you agree)

**Comment by alejandronanez** [comment]
Para complementar, me parece que el formato de la charla en inglés podría ser tipo _lightning talk_, 10-15 minutos de un tema en especifico. Por ejemplo, algo como _Lodash en 10 minutos_

**Comment by jdjuan** [comment]
![all-the-things-charlas-en-ingls-aprobadas](https://cloud.githubusercontent.com/assets/3171900/25814312/a97f8d0e-33e2-11e7-9a16-ee6569c4b846.jpg)
