### ISSUE TITLE
Coding Dojo

### ISSUE THREAD

**Issue by achanci** [angular-medellin/meetup#10]
# Coding Dojo

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción
Me gustaria que se hicieran Coding Dojos y Katas para asimilar mejor el desarrollo y la arquitectura con Angular, en especial para los que apenas estamos comenzando, como yo :)

En el meetup anterior observé que muchos integrantes tienen buenos conocimiento, por lo que no seria dificil conseguir algunos sensei

**Comment by alejandronanez** [comment]
Me apunto para sensei =]

**Comment by jdjuan** [comment]
@achanci me encanta la idea! 🥇 Creo que muchas personas desean que hagamos un ejercicio más práctico en Angular.  En el próximo meetup probablemente lleguen más de 100 personas por lo tanto necesitaremos una mano ✋ ¿Quién se anima!? 😀 

## **Necesitamos al menos 5 senseis** :neckbeard: para hacer el coding dojo

### Primer Sensei: @alejandronanez 💪

**Comment by CrisDan1905** [comment]
Me encantaria ser sensei pero aun soy un pequeño saltamontes (jeje) Aun me falta afianzar conocimientos, pero espero pronto serlo. Ojalá se animen mas personas a ser sensei y podamos hacer un buen coding dojo :smiley:

**Comment by danielcb29** [comment]
Hey!, no soy super experto pero puedo ayudar en la parte práctica. Cuentes conmigo as a sensei 😀

**Comment by ltciro** [comment]
Hola,  no soy experta pero para este tema me gustaría apoyar como "sensei"  :heart_eyes_cat:

**Comment by jdjuan** [comment]
@alejandronanez  @danielcb29 @ltciro ha llegado la hora de brillar como senseis! 🤙 

¿Puedo contar con su ayuda para el próximo meetup? 😀

**Comment by alejandronanez** [comment]
Nunca he estado en un coding dojo, pero igual firme. 😎

**Comment by danielcb29** [comment]
@jdjuan Firme también  😎

**Comment by alejandronanez** [comment]
@jdjuan el meetup del 3 de Junio es el coding dojo? o vamos a hacer otro aparte?

**Comment by ltciro** [comment]
Con todo el gusto :grinning:

**Comment by Fabian-Buitrago** [comment]
Hola, estoy interesado en colaborar, nunca he estado  en un evento de esta clase pero me apunto para sensei

![image](https://cloud.githubusercontent.com/assets/9866446/26413450/aa7090b4-4071-11e7-9547-e9489ba713ba.png)
