### ISSUE TITLE
Quiero participar en  el  Angular Labs 10 de febrero 2018

### ISSUE THREAD

**Issue by Xiomy1311** [angular-medellin/meetup#100]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Mi nombre es Xiomara Zapata Vasquez,  trabajo como desarrollodora .NET hace 6 años.  
Resulta  que voy a iniciar un proyecto con Angular y me encuentro estudiando hace un mes aproximadamente.  

Por lo anterior me gustaría participar, ademas seria mi primera vez con la comunidad y muy  bueno que tuvieran una chica participando en medio de tantos hombres!! 😎

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @Xiomy1311! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
