### ISSUE TITLE
Participar en Angular Lab

### ISSUE THREAD

**Issue by afgomez123** [angular-medellin/meetup#101]
# Me gustaría:

* [x] 😁 Participar de los Angular Labs

## Descripción

Soy Andrés Gómez Ingeniero de sistemas , quiero participar en los angular labs ya que tengo como propósito aprender Angular en este año, mi primer acercamiento fue en el Meetup del 27 de enero del 2018.

Actualmente no tengo experiencia desarrollando con el Framework , me gustaría ser aceptado y capacitado ya que de esta manera podría aprender lo suficiente del tema .

<img width='50%' src='https://media.giphy.com/media/IQwaRpQ5QB5ZK/giphy.gif'>

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @afgomez123! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
