### ISSUE TITLE
Participación Angular Labs/10Feb

### ISSUE THREAD

**Issue by afvalenciab** [angular-medellin/meetup#102]
# Me gustaría...

* [x] 😁 Participar de los Angular Labs

## Descripción 
Buenos días!
Este issue es para participar en el Angular Labs

**😃 Quién eres:** 
Soy Andres Felipe Valencia Benitez, Ingeniero de Sistemas, estudiante activo de Platzi, interesado en aprender tecnologías nuevas con el objetivo de aplicarlos en proyectos personales y en el ámbito laboral. 

😁 Por qué quieres participar de los Angular Labs:
Deseo participar en el Angular Labs para seguir aprendiendo y mucho mejor si es de los expertos, crear buenas relaciones profesionales, estoy iniciando un proyecto en la empresa en Angular por lo que me gustaría mucho conocer las buenas practicas del desarrollo en Angular, adicionalmente seria mi primera participación en Angular Medellín lo cual me llena de emoción poder incorporarme en el equipo.

🤓 Cuánto tiempo llevas codificando en Angular:
Llevo aproximadamente 3 meses aprendiendo a codificar en Angular, he creado proyectos de pruebas a modo de practica.

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @afvalenciab! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
