### ISSUE TITLE
Labs: Camilo Martinez

### ISSUE THREAD

**Issue by equiman** [angular-medellin/meetup#103]
# Me gustaría participar en los labs, cuento con una certificación en HTML5/CSS/JS y llevo trabajando 7 años en desarrollo front end y movilidad híbrida. 

Hice un curso en Udemy cuando salió Angular 2 https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/overview con Maximilian Schwarzmüller.

Me gustaria reforzar los conocimiento y combinarlos con NativeScript.

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [X] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

**Comment by pablovem** [comment]
¡ @equiman  !

¡Queremos agradecerte por participar de los Angular Labs! 👍 Lamentamos decirte que no ha sido seleccionado en esta ocasión 😢. La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

¡Pero eso no importa! Porque tenemos un premio para ti por haber aplicado. 
!Ven a nuestro próximo meetup y búscanos para entregártelo! 🎉
