### ISSUE TITLE
Solicitud para participar en Angular Lab #1

### ISSUE THREAD

**Issue by Oesoto** [angular-medellin/meetup#104]
Soy Oscar Soto, ingeniero de sistemas. Hasta hace menos de un año venía trabajando en desarrollo de experiencias interactivas y ahora estoy mas involucrado en proyectos de desarrollo web.

Considero que el conocimiento compartido en la comunidad de Angular es de alta calidad y sería una oportunidad perfecta para comenzar a tener bases sólidas para desarrollar aplicaciones con las últimas caracteristicas del framework. A futuro me gustaría que este conocimiento abra caminos para compartir con otros miembros de la comunidad o crear oportunidades de emprendimiento o negocio.

Llevo menos de 6 meses codificando en AngularJS y con mucho interés de migrar a la ultima versión de Angular

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @Oesoto! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
