### ISSUE TITLE
Solicitud Angular Lab No. 1

### ISSUE THREAD

**Issue by KevinMalo** [angular-medellin/meetup#105]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [X] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción

😃 Quién eres: Soy estudiante inicial de ing. de software, soy de los Lllanos donde podría asegurar no hay eventos como estos y en mis tiempos libres soy desarrollador web.

😁 Por qué quieres participar de los Angular Labs: Para mi es una necesidad ya que podría asimilar muchos conceptos que tengo en el aire sobre el framework, ademas de poder conocer a más gente 'Angulera - angular (?)'.

🤓 Cuánto tiempo llevas codificando en Angular: He desarrollado algunas apps y seguido el paso a algunos cursos y tutoriales, pero no considero que sea un profesional o tenga años de experiencia a pesar de conocer el framework desde la versión 2.

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @KevinMalo! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
