### ISSUE TITLE
 Angular Labs

### ISSUE THREAD

**Issue by horaas** [angular-medellin/meetup#106]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x ] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
 Angular Labs
Hola mi nombre es Arturo Horacio Segovia

Me gustaria participar en AngularLabs por que me apasiona el desarrollo y cada día quiero obtener muchos mas conocimientos para aplicarlos en mi ambito laboral.

llevo muy poco tiempo desarrollando en angular si experiencia en angular.

Saludos a toda la comunidad.

**Comment by pablovem** [comment]
¡ @horaas  !

¡Queremos agradecerte por participar de los Angular Labs! 👍 Lamentamos decirte que no ha sido seleccionado en esta ocasión 😢. La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

¡Pero eso no importa! Porque tenemos un premio para ti por haber aplicado. 
!Ven a nuestro próximo meetup y búscanos para entregártelo! 🎉
