### ISSUE TITLE
Felipe Rivera

### ISSUE THREAD

**Issue by apipe1113** [angular-medellin/meetup#107]
😃 Soy Felipe Rivera Londoño
😁 Quiero participar en los Angular Labs para aprender más sobre angular
🤓 1 mes codificando en Angular

**Comment by jdjuan** [comment]
Hooola @apipe1113 ! 😄 

Te cuento que ya escogimos los ganadores de esta ocasión! Pero esperamos publicar otra edición para el próximo mes! 👍
