### ISSUE TITLE
Propuesta Canal Slack

### ISSUE THREAD

**Issue by xhasur** [angular-medellin/meetup#11]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [X] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

Porque no  creamos un canal en slack "medellin angular" en el cual podamos discutir , hablar , colaborarnos y hasta poder com,partir informacion  ; de igual forma por este medio podemos seguir alimentandolo con los pytos que realizemos y con "documentacion"

**Comment by alejandronanez** [comment]
Súper la idea!
Aunque me gustaría proponer Gitter o Discord en vez de Slack.
Slack cuando es gratuito limita el historial de mensajes a 10K y de ahí en adelante empieza a archivar todo.
+ Gitter se integra muy bien con github, se pueden linkear issues/prs etc.

**Comment by jdjuan** [comment]
Gracias por tu propuesta @xhasur ! 🏋️ 💪 
Yo soy terrible cuando se trata de chatear, pero estoy seguro que otros miembros que pueden encontrar muy efectivo este canal de comunicación.

@alejandronanez no conocía Discord, se ve prometedor! 👍 

La implementación de esta mejora dependerá de la acogida de los miembros. Si lo piden, lo hacemos! 👊

**Comment by xhasur** [comment]
@alejandronanez que te parece si creamos ese canal donde dices ??? y lo compartimos?

**Comment by alejandronanez** [comment]
@xhasur sí, entiendo la facilidad de Slack pero creeme que cuando pasemos los 10K mensajes slack se vuelve un PITA.

> La implementación de esta mejora dependerá de la acogida de los miembros. Si más personas lo piden, lo hacemos

@jdjuan podríamos arrancar con uno o dos meses de prueba a ver si tiene acogida, sino, pues _cerramos la llave_ y listo 😄

**Comment by xhasur** [comment]
me a trevi a crearlo ..

https://gitter.im/angular_medellin/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

quedo atento !!

**Comment by jdjuan** [comment]
@xhasur gracias por crear el gitter! 🥇 Las personas que toman la iniciativa como vos hacen que esta comunidad siga adelante!

Poder integrar al máximo nuestro Gitter con este repositorio nos permitiría referenciar issues como lo mencionó @alejandronanez pero además suscribirno a diferentes actualizaciones como PRs, comments, commits, entre otros! 🎉 Esto nos permitiría tener un canal de comunicación más activo que puede ser de mucha ayuda para nuestra comunidad 👍 

Para sacar todo el provecho de esto debí autorizar el Gitter pero no pude hacerlo porque no fue creado desde la organización `github.com/angular-medellin` 😢 

Así que tuve que crear otro Gitter para realizar la integración 😅 disculpa @xhasur

### **Gitter:** https://gitter.im/angular-medellin

En general el Gitter me parece una iniciativa muy válida @xhasur @alejandronanez , así que pretendo anunciarla oficialmente en el próximo meetup y entonces evaluaremos si tiene la acogida que queremos. ¿Les parece? 🙂

**Comment by alejandronanez** [comment]
@jdjuan creo que mejor mande un mensaje por meetup de una vez! por qué esperar 😄 
@xhasur súper 👍

**Comment by xhasur** [comment]
jaja no problem !!! (y)

**Comment by jorgeherrera9103** [comment]
Hola, ya estoy en el gitter, no lo conocia muy bacano.
