### ISSUE TITLE
Unit Testing w/ Angular

### ISSUE THREAD

**Issue by nicobytes** [angular-medellin/meetup#111]
# Me gustaría...

* [x ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

### Unit Testing w/ Angular

En proyectos desarrollados con Angular podemos escribir pruebas a cada uno de los artefactos (servicios, componentes, directivas) en esta charla veremos como escribir estas pruebas y conocer los indicadores para saber qué partes debemos probar.

### Speaker

Nicolas Molina Monroy
Fronend Senior en Senseta y Desarrollador Front-end especializado en el área de FrontEnd & HybripApps, enfocado en el aprendizaje y enseñanza de JS.
Soy docente del curso de testing en angular para escuelaIT y creador ng-classroom.com sitio enfocado al aprendizaje y buenas prácticas en desarrollo con Angular.

**Comment by jdjuan** [comment]
Súper @nicobytes  ! 😁 Éste es un tema muy necesario en Angular! 🅰️  
Creo que puedes ser el próximo speaker invitado de nuestro meetup! 🥇 
Estoy seguro que la sacarás del estadio 🎉
