### ISSUE TITLE
Entendiendo el NgZone (zone.js)

### ISSUE THREAD

**Issue by henryzarza** [angular-medellin/meetup#115]
# Me gustaría...

* [x] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Me llamo Henry Zarza, soy estudiante de décimo semestre de ingeniería informática y desarrollador web frontend en Angular y Reactjs, también manejo algo de backend con Nodejs, llevo trabajando con Angular 1 año y 6 meses. Me parece que el NgZone es un tema muy importante para entender el funcionamiento del Change Detection en Angular, para que sirve y como con este podemos mejorar el rendimiento de nuestras aplicaciones.

**Comment by jdjuan** [comment]
Súper @henryzarza  ! 😁 Éste es un tema muy necesario en Angular! 🅰️ Yo ni siquiera lo conozco bien, así que será genial que alguien nos cuente cómo funciona! 🌟

No olvides echarle un ojo a nuestros **[Speaker Guidelines](https://github.com/angular-medellin/meetup/blob/master/assets/SPEAKERS.md#-speakers-)** para que la saques del estadio 🎉 

Envíame tus diapositivas cuando estén listas para darte feedback! ⚡️
