### ISSUE TITLE
Charla Angular Universal

### ISSUE THREAD

**Issue by Krank2me** [angular-medellin/meetup#117]
* [X] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Introducción a Angular Universal

Angular Universal es la tecnología que te permite ejecutar una aplicación Angular desde el servidor, haciendo que el tiempo de carga del DOM sea mucho menor. El Server Side Rendering (SSR) puede ser interesante por cuestiones de SEO, para compartir páginas en redes sociales (con su thumbnail), o para reducir el tiempo de carga inicial.

## Quien soy...

Mi nombre es Frank Alejandro Betancur, soy Java Developer (muy orgulloso de serlo 😎) trabajo acualmente en Intergrupo de outsourcing en Sura. Desde octubre ando metido estudiando JS y sus sabores, de los cuales me he enamorado de Angular y ya he hecho cositas interesantes en él, soy co-organizados de MedellinJS, me encanta compartir conocimiento y generar comunidad, me gusta hacer deporte (aunque no se me note) especialmente Karate-do, estudiar, aprender cosas nuevas, pasarla con mis amigos y la cultura hip hop!

## Que necesitamos...

simplemente ATITU!!!

**Comment by Krank2me** [comment]
las slides:
slides.com/elpanda/angular-universal

**Comment by jdjuan** [comment]
Genial @Krank2me ! 😀 
Vas seguro como speaker para nuestro próximo meetup! La próxima semana déjame nos reunimos por Hangouts para darte un poco de feedback, pero ya vas seguro! 🚔

**Comment by Krank2me** [comment]
Claro que si Juan!!! Quedo pendiente!!! Muchas gracias
