### ISSUE TITLE
NativeScript en Español

### ISSUE THREAD

**Issue by mendokar** [angular-medellin/meetup#119]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [X] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción

https://medium.com/@oscar.mendoza93/nativescript-en-espa%C3%B1ol-4f0f7e759832

Cordial Saludo.

este es un post el cual me gustaría compartir en Angular Medellin para poder compartir con la comunidad mis conocimientos con NativeScript Angular y Firebase.

**Comment by jdjuan** [comment]
@mendokar Genial! Ambas publicaciones!. Éste post en particular es más una introducción, así que te voy a sugerir que la agreguemos al otro post para tenerlo todo junto. 😼 

Continúo la traza en #120 🙂
