### ISSUE TITLE
Tema Unit Testing, Karma, Protractor ...

### ISSUE THREAD

**Issue by royalcas** [angular-medellin/meetup#12]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

Seria intenerante tener una charla de pruebas unitarias en javascript mostrando:

- Unit Testing
- Dependency Injection
- Mocking, tips
- Pruebas con Protractor (E2E)
- Pruebas Con Karma

Yo podría aportar con este tema

**Comment by jdjuan** [comment]
Maravilloso @royalcas ! 💪 

¿Crees que podrías preparar una charla de estos temas?
¡Estoy seguro que sería un tema bien interesante! Muchas personas quieren a empezar a escribir sus pruebas en Angular y aún no saben cómo 👍

**Comment by royalcas** [comment]
Por supuesto @jdjuan  !

Iniciare preparando un material para la charla y me comunicaré cuando algo para mostrar!

Gracias!
