### ISSUE TITLE
Convertir en librería un proyecto creado con angular/cli

### ISSUE THREAD

**Issue by angiefrancop** [angular-medellin/meetup#13]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [x] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Hola a todos, me gustaría saber si pueden ayudarme. Tengo un proyecto creado con angular/cli (@angular/cli@1.0.3) el proyecto es un buscador de puntos en google maps y me gustaría saber como compilarlo para que sea una libraría.

Gracias!

**Comment by jdjuan** [comment]
Hola @angiefrancop ! , al parecer @alejandronanez en #2 también quiere saber cómo hacer esto. Probablemente en nuestro próximo meetup vamos a hacer una librería en Angular 🤘 

Mientras tanto así es como puedes crear una librería:

1. La mejor manera (y la más fácil) actualmente de crear una librería es utilizando [el generador de Jurgen Van de Moere](https://github.com/jvandemo/generator-angular2-library/). En este repositorio están especificados todos los pasos para hacerlo.

2. Después de haber utilizado el generador, probado localmente y funcionado, sólo basta con que pongas tus archivos dentro de la carpeta `src` y exportes el contenido para luego ser consumido por otra aplicación.

Estoy seguro que tendrás preguntas más específicas, no dudes en volver aquí cuando las tengas, seguro también le serviran a otras personas 😸

**Comment by alejandronanez** [comment]
@angiefrancop para complementar un poco, podrías agregar [TravisCI](https://travis-ci.org/) o [Circle](circleci.com) para automatizar el proceso de publicación de tu módulo a NPM.
Para hacer pruebas locales con tu paquete no es necesario publicar cada cambio a npm, basta con utilizar `npm link`.
No quiero entrar en tanto detalle por este medio porque se sale del scope del repo, pero si tienes dudas te puedo colaborar por privado con mucho gusto. 👍

**Comment by jdjuan** [comment]
¡Lo veremos en nuestro próximo meetup! 👍
