### ISSUE TITLE
Componentes dinámicos

### ISSUE THREAD

**Issue by cesar2064** [angular-medellin/meetup#14]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Hola a todos, me gustaría proponer como tema componentes dinámicos, debido a que es muy útil sobre todo cuando uno hereda funcionalidad de otras clases y desea en cada clase que hereda renderizar componentes diferentes.

**Comment by jdjuan** [comment]
@cesar2064 échale un ojo a esto que salió en Angular 4

https://angular.io/api/common/NgComponentOutlet
