### ISSUE TITLE
"Redux" con angular 2/4

### ISSUE THREAD

**Issue by cesar2064** [angular-medellin/meetup#15]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Me gustaria que se tocara el tema de como usar "Redux" con angular 2/4 así como lo indica esta libreria https://github.com/ngrx/store.

**Comment by luchillo17** [comment]
Me gustaria postularme, conozco la librería, además de trabajar con ella haciendo uso junto con `@ngrx/effects` para manejar eventos asíncronos como llamadas a apis.

**Comment by jdjuan** [comment]
Súper @luchillo17 ! 🤙 

Este tema es de mucha relevancia para la comunidad!, así que tienes una gran responsabilidad 👕 

Échale un ojo a **[este archivo](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)** y empieza a hacer tus diapositivas. Cuando las tengas listas, las compartes aquí y yo te doy feedback! 😀

**Comment by luchillo17** [comment]
Juan que parte de Redux es la que busca la comunidad? la introducción y teoria?, o la practica como formato de workshop?

**Comment by jdjuan** [comment]
@luchillo17 una introducción con un ejemplo práctico estaría muy bien! 😁
