### ISSUE TITLE
¿Es posible recibir un evento emitido por un componente descendiente desde un componente ancestro?

### ISSUE THREAD

**Issue by CrisDan1905** [angular-medellin/meetup#17]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [x] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

No se si es clara mi duda. Tengo 3 componentes, los cuales estan anidados mediante sus templates asi

componente_hijo ------> componente_ppal -----> componente_padre

Se que mediante un event Emmiter puedo enviar data desde el componente hijo hacia el ppal. Pero que pasa si esa data la necesita es el componente padre?? Debe pasar primero por el ppal y luego volverlo a emitir hacia el padre o hay alguna manera de que lo reciba directamente el componente padre??

Muchas gracias :smiley:

**Comment by alejandronanez** [comment]
@CrisDan1905 [esta](http://stackoverflow.com/a/34703015/1405803) respuesta en Stackoverflow se ve bastante completa. Ojalá te sirva. 👍

**Comment by CrisDan1905** [comment]
Muchas gracias @alejandronanez por lo que veo la manera como se recomienda es mediante un servicio que compartan ambos componentes y eso era justo lo que quería evitar ya que utilizar un servicio me genera un acoplamiento que no deseo :sweat: jajaja bueno, que mas da... veré como me las arreglo a ver si puedo evitar el servicio... :+1:

**Comment by jdjuan** [comment]
@CrisDan1905 éste es un tema bien interesante 🌟  creo que la mayoría de personas que empiezan a trabajar con Angular se hacen la misma pregunta que tú. Existen muchas alternativas y su eficiencia depende del contexto y las necesidades que tengas en el proyecto

Por ahora te recomiendo darle like a #15 que es tal vez una manera interesante de resolver tu problema 👍 

Y lo podemos tocar más a fondo en nuestro próximo meetup!

**Comment by jdjuan** [comment]
¡Ah y este video menciona cómo lo resuelve! 
### [VIDEO](https://youtu.be/cyaAhXHhxgk?t=149)

**Comment by jdjuan** [comment]
@CrisDan1905  seguro ya lo resolviste 🥇
