### ISSUE TITLE
¿Como puedo realizar un GET a una API REST con query params?

### ISSUE THREAD

**Issue by CrisDan1905** [angular-medellin/meetup#18]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [x] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Alguno podria resolverme esta duda porfa??
Es que he estado tonteando un poco consumiendo una api rest con datos dumb (por cierto, para quien le interese, aqui les dejo el link: [https://jsonplaceholder.typicode.com/](url). Está bastante bueno para probar las consultas HTTP y aprender a consumir apis y todo eso)

El punto es que necesito hacer una consulta con query Params para poder obtener un dato en particular. He intentado mil cosas y no he conseguido lograrlo, siempre me devuelve todos los datos y en   el network del navegador no veo que ponga el query Param. Deberia ser algo asi: [https://jsonplaceholder.typicode.com/users?id=1](https://jsonplaceholder.typicode.com/users?id=1)

pero no me pone el query param al final. Probe de 2 formas distintas y ninguna de las dos funciono. 
Aqui está el codigo:

```
  private baseURL: string = 'https://jsonplaceholder.typicode.com';


  obtenerDetalles(id: string): Observable<any> {
    let header: Headers = new Headers;
    header.set('id', id);

    let optiones = new RequestOptions();
    opciones.headers = header;
    return this._http.get(this.baseURL + '/users', opciones).map((res: Response) => res.json())
  }
```
Aquí está la otra manera que tampoco funcionó: 

```
   private baseURL: string = 'https://jsonplaceholder.typicode.com';

   obtenerDetalles(id: string): Observable<any> {
     let header: Headers = new Headers;
     header.set('id', id);

     let opciones = new RequestOptions();
     options.headers = header;
     return this._http.request( new Request({
       method: RequestMethod.Get,
       url: this.baseURL + '/users',
       search: 'id='+id
     })).map((res: Response) => res.json())
   }
```

Alguien que me pueda echar una mano  por favor! :sweat: 

Por cierto, tambien tengo un repositorio con la app, es un desastre porque estoy probando todo el tema de rutas de angular, pero por si alguien quiere echarle un vistazo y ver cosas sobre esto de las peticiones y las rutas o ayudarme y ver un poco mejor como está la cosa :grin:

[https://github.com/CrisDan1905/prueba-routing-angular](https://github.com/CrisDan1905/prueba-routing-angular)

**Comment by alejandronanez** [comment]
Cristian, viendo por encima, tiene un error con las variables que estas declarando. Tienes:
```js
let opciones = new RequestOptions();
options.headers = header;
```
Debería ser
```js
let options = new RequestOptions();
options.headers = header;
```
Esto aplica para los dos ejemplos, es lo primero que llama mi atención a primera vista.

**Comment by CrisDan1905** [comment]
@alejandronanez gracias, pero no es ese el error. Lo que pasa es que realmente en mi codigo estaba manejando esas variables en ingles pero a la hora de pasarlas acá al issue preferi ponerlas en español para que no se viera tan chocante ese espanglish y se me quedó esas en ingles jajajaja :grin: El caso es que el problema no es ese porque en mi codigo estan todas bien escritas, Ya lo verifique

**Comment by jdjuan** [comment]
@CrisDan1905 ya has intentado utilizar **[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)**? 🤔 

No sé cuál es la diferencia entre los parametros `search` y `params` del `RequestOptions` pero ambos aceptan objetos de tipo `URLSearchParams`.

![screenshot-angular io-2017-05-14-22-39-10](https://cloud.githubusercontent.com/assets/3171900/26041915/743215c2-38f6-11e7-994a-53ed0206dc6f.png)

Si tampoco te funciona, entonces aisla el problema en un repo y yo mismo lo clono, y te paso la solución 🙂

**Comment by jdjuan** [comment]
Suponemos que has resuelto el problema 👍
