### ISSUE TITLE
Almacenamiento de links y recursos en el repositioro Github

### ISSUE THREAD

**Issue by cortizqgithub** [angular-medellin/meetup#19]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
En este repositorio debe quedar de alguna forma todos los enlaces y referencias que se están colocoando en las discusiones del Meetup.

**Comment by jdjuan** [comment]
Hola @cortizqgithub ! Tienes razón, muchos links interesantes se han compartido en Meetup.com y en el Gitter. Pero sería maravilloso centralizarlos y ponerlos en un documento 💪 

@MelinaMejia95 hizo esto con los recursos para aprender inglés en #8 ¿Qué tal si tú nos ayudas (o alguien más) con un Pull Request en el que agregues un archivo llamado `RECURSOS.md` y que contenga algunos de ellos? 😎 

Luego la comunidad se puede encargar de alimentar el documento con más información 📣

**Comment by jdjuan** [comment]
Completado en #28 👍
