### ISSUE TITLE
Módulos

### ISSUE THREAD

**Issue by alejandronanez** [angular-medellin/meetup#2]
# Cómo crear un plugin/modulo?

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción
Sería bueno una charla sobre cómo crear modulos para Angular para luego importarlos:

`import Foo from '@foo/my-module`

**Comment by jdjuan** [comment]
Gracias por tu aporte @alejandronanez 💪 Seguramente este tema va muy bien con:

- JavaScript modules
- Module formats (UMD, AMD, CommonJS)
- Module loaders
- Module bundlers

Sería bueno que alguien nos contara a grandes rasgos qué significan y cómo los podemos utilizarlos. Podrías ser tú mismo o alguien más.

[Aquí hay más información](https://jvandemo.com/a-10-minute-primer-to-javascript-modules-module-formats-module-loaders-and-module-bundlers/).

**Comment by jdjuan** [comment]
@alejandronanez después de releer el issue creo que incialmente te referías a cómo hacer una librería para angular, verdad? 😅 Pues yo puedo dar ese tema!, últimamente he estado trabajando bastante en la creación de librerías de Angular. ¡Déjame yo me encargo de preparala! 💪

**Comment by CrisDan1905** [comment]
@jdjuan si es eso lo que @alejandronanez dice me parece genial la idea. La apoyo 100% llevo un tiempo trabajando con Angular pero me está llamando la atención la idea de realizar librerías o hacer wraps para Angular. Cuenten conmigo

**Comment by alejandronanez** [comment]
@jdjuan a eso me refería. Parece que ya hay tema para el siguiente meetup entonces ✌🏼

**Comment by jdjuan** [comment]
¡Lo veremos en el próximo meetup!
