### ISSUE TITLE
Angular Camp

### ISSUE THREAD

**Issue by garraxxi** [angular-medellin/meetup#20]
# Angular Camp.  

- [x] **Otro**

## This summer make friends as you master new tech skills
A Community-driven event that puts together developers like you.

July 6th–7th, 2017

Para aquellos que tengan la posibilidad de asistir y luego retroalimentar al meetup.

Saludos

**Comment by cortizqgithub** [comment]
Esto dice que es en Barcelona, tiene costo?

**Comment by garraxxi** [comment]
Si si tiene costo, verifique ver las [tarifas](https://angularcamp.org/)
