### ISSUE TITLE
Propuestas para una próxima reunión (Speakers incluidos)

### ISSUE THREAD

**Issue by MelinaMejia95** [angular-medellin/meetup#21]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Hola! 
Tengo dos personas que podrían colaborarnos dando dos charlas! :grinning:
- Juan David Sanchez: Vue o React (Ya ha dado charlas en Medellín JS).
- Santiago Molina: Sass, Atomic Design, BEM y SMACSS.

Si les llama la atención, me pongo en contacto con ellos para programarlos en una próxima reunión! :v:

**Comment by jdjuan** [comment]
¡Qué bien! @MelinaMejia95 gracias por proponer no sólo los temas sino también los speakers 😎 

- La charla de Vue o React me gustaría enfocarla hacia una comparación de tecnologías, algo así como: **Angular, React y Vue: ¿Cuál utilizar?** en la que los asistentes puedan, de una vez por todas, entender en qué escenarios es conveniente utilizar qué tecnologías 🔥 Sólo haría falta un experto por cada tecnología para tener una perspectiva mayor. ¿Qué opinas? ¿Juan Sanchez podría ser un experto en Vue o React?

- En cuanto a la de Sass, Atomic Design, BEM y SMACSS, ¡Vaya!, sí que son temas interesantes 🐤 Pídele por favor a Santiago Molina que cree un issue aquí y nos explique los detalles de la charla 👏

**Comment by alejandronanez** [comment]
@jdjuan @MelinaMejia95  IMHO es muy difícil encontrar una respuesta _correcta_ para `Technology #1 vs Technology #2`, por ejemplo, hay aplicaciones pequenas/medianas/gigantes que se pueden hacer igual en Vue/React/Angular/Any New Trendy Js Framework. Además creo que hacer charlas de otros frameworks (que son _competencia directa_ de Angular) en un meetup de Angular no es lo correcto, lo que me parece correcto es hablar sobre tecnologías que pueden mejorar el desarrollo en Angular, por ejemplo Immutable.js / Redux / Testing frameworks / RxJS / `async/await` / `generators` / etc...

**Comment by jdjuan** [comment]
Hola @alejandronanez ! gracias por participar de esta discusión! 👍 
Verás, en Angular Medellín queremos que la diversidad sea un pilar fundamental, no sólo culturalmente, sino también tecnológicamente.

Cuando sólo tenemos un martillo, todos los problemas parecen clavos. Cuando tenemos una caja de herramientas, los desafíos tecnológicos se hacen más viables 😲 

La verdad es que cuando vi este issue pensé lo mismo que tú 😕 no sabía cómo responder.
Pero luego pensé en todo el provecho que podríamos sacar si sabemos canalizar estas discusiones de la manera correcta.

Una comparación de frameworks nos podrías dar insights para identificar las fortalezas y debilidades de Angular, algo clave a la hora de afrontar retos tecnológicos 🌟🌟🌟

**Comment by MelinaMejia95** [comment]
@jdjuan @alejandronanez Bueno, creo que ambos tienen razón en muchas cosas. Cuando encontré un speaker me emocioné tanto que no pensé bien en que los temas deberían ser relacionados con Angular :sweat_smile: Lo siento. 
Seguiré buscando entonces alguien que sepa de Angular que pueda colaborarnos en una charla! :relaxed:

**Comment by khriztianmoreno** [comment]
Busquemos que el foco de la comunidad sea angular y no se nos vuelva un popurry de cosas, este meetuo se vuelve mas especializado en una tecnologia como lo es angular y cuando es algo mas general esta comunidades como MedellinJS que se enfocan mas en dar una introduccion a los temas.

**Comment by jdjuan** [comment]
@khriztianmoreno gracias por compartir tu punto de vista, creo que es muy válido.
@MelinaMejia95 te reitero el agradecimiento por tu proactividad, así se hace! 👍 Cerraré el issue ya que #23 está abierto! 🐤
