### ISSUE TITLE
Sass, Atomic Design, BEM y SMACSS

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [angular-medellin/meetup#23]
# Me gustaría ...  

- [x] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Mucho gusto, mi nombre es Santiago Molina Orozco.
### Un poco sobre mi:

- Desarrollador web full stack y mobile, CoFundador de [Justbit](https://www.justbit.site) donde nos enfocamos en el UX y UI de nuestras aplicaciones.

- Actualmente me enfoco en React en el front-end y Rails en el back-end ( Con algo de experiencia en AngularJS ).

### Sobre  la charla: 

- Más que enseñar SASS ( Sobre lo cual hay muchos cursos tanto gratuitos como de pago en internet ), es invitarlos a utilizar cualquier pre-procesador de CSS, como pueden ser LESS, STYLUS o SASS, mostrando algunas de sus principales ventajas.

- Diferencias entre SASS y SCSS,siendo más usado hoy en dia SCSS por el motivo de que todo archivo CSS es un archivo de SCSS, pero en lo personal, prefiero SASS, como programador de Ruby soy partidario del principio DRY “Don't Repeat Yourself”, eso me lleva a usar HAML sobre HTML.

- Al usar Frameworks como Bootstrap, que ventajas nos trae su versión en SASS.

- Entender en qué casos usar estos preprocesadores y en cuáles no, ya que aunque son una gran herramienta, podríamos llegar a hacer un doble trabajo.

- Para finalizar se hablará de cómo combinar BEM con Atomic Design y SMACSS en nuestros proyectos, como un buen patrón para nuestra nomenclatura de clases y scaffold, usando poderes en SASS para la optimizacion de codigo.

### Lo que no se abordará en esta charla pero podríamos hacerlo más adelante:

- Sintaxis de SASS.

- Frameworks como Compass.

- Web components con SASS

- Pre-Procesadores de HTML y JS.

	“We’re not designing pages, we’re designing systems of components.”
	-Stephen Hay.

### Referencias:

- [SASS](http://sass-lang.com/)

- [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/)

- [BEM](http://getbem.com)

- [SMACSS](https://smacss.com/)

**Comment by jdjuan** [comment]
@SantiagoMolinaOrozco Woohoo! 🔥 
¡Qué buena charla! Veo que la has estructurado muy bien 🎖 

Tu charla es completamente bienvenida, en nombre de la comunidad te agradecemos por tu proactividad.

Para aquellos que no lo saben:
> En Angular también podemos utilizar SASS o SCSS con el comando: `ng new stlye=scss`

@SantiagoMolinaOrozco en Angular Medellín lo ponemos mucha atención al contenido que le mostramos a nuestros miembros, darle el enfoque adecuado a la charla será clave para salgas en hombros del auditorio 🎉 

Tan pronto como tengas los slides terminados, envíame un email (`david.juanherrera@gmail.com`), ambos revisaremos la presentación y le daremos luz verde para presentarla en el meetup. 👍

**Comment by jdjuan** [comment]
@SantiagoMolinaOrozco acabo de subir unas recomendaciones para los speakers de Angular Medellín, échale un ojo! 👀  

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**
