### ISSUE TITLE
Angular Mix

### ISSUE THREAD

**Issue by garraxxi** [angular-medellin/meetup#24]
[Angular Mix](https://angularmix.com).

- [x] **Otro**

Otra actividad para aquellos que puedan acceder a ella.

[Ver tarifas](https://angularmix.com/#!/register)

También tiene la opción para [reserva de hotel](https://res.windsurfercrs.com/ibe/details.aspx?propertyid=14843&nights=1&checkin=10/03/2017&group=GMREA63).

Espero que algunos miembros del meetup puedan asistir y luego compartir la experiencia.

**Comment by jdjuan** [comment]
@garraxxi ! Gracias por compartir esta información! 🎖 

Queremos que todos estos recursos que nos estás compartiendo puedan ser accedidos por otros miembros a lo largo del tiempo, no queremos que se pierdan entre otros issues 🤔 

Pensamos que agregar un archivo a este repositorio sería de gran ayuda para centralizar estos recursos (#20 #24), pero necesitamos alguien que nos ayude hacerlo, te gustaría tomar este rol? 🔥 Mira #19

**Comment by danielcb29** [comment]
@jdjuan Yo te ayudo a centralizar esos recursos en un MD. 👍. Existe algun protocolo especifico para contrinuir? O solamente fork y PR?

**Comment by garraxxi** [comment]
@jdjuan Puedo seguir aportando si ya hay un responsable de hacerlo o si no, bien puedo asumir el rol. Saludos!

**Comment by danielcb29** [comment]
@garraxxi Seria interesante que revisaras mi PR cuando lo abra para ver si se me paso algo. Te dejo link en el issue apenas lo abra

**Comment by alejandronanez** [comment]
Tal vez pueden seguir el formato que tienen acá. https://github.com/AngularClass/awesome-angular

**Comment by jdjuan** [comment]
@danielcb29 por ahora sólo basta con un PR y un fork 👍 luego crearemos un manual de contribución
@garraxxi ¿Qué tal si revisas el PR de @danielcb29 ? 😃 
@alejandronanez Buena idea ! 🥇

**Comment by danielcb29** [comment]
Aquí esta: https://github.com/angular-medellin/meetup/pull/26
Quedo pendiente a las actualizaciones del PR
