### ISSUE TITLE
Creemos un meetup accesible para personas con discapacidades visuales

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#25]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [x] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Nuestra labor es cerrar brechas. Así que hagamos que nuestros contenidos, presentaciones y talleres sean contenidos accesibles para personas con dispacidades visuales. Recolectemos las herramientas necesarias para lograrlo.

¿Quién se une? ¡Necesitamos ideas! 💡💡💡

**Comment by teffcode** [comment]
Hola ! 🙋🏻

Te cuento que en mi anterior trabajo, tuve una capacitación sobre "cómo tratar con personas en situación de discapacidad". Quien nos brindó la charla y las actividades fue un grupo de la UdeA llamado "Guía Cultural", fue excelente su ayuda, no sabes ! Pienso que ellos podrían brindarnos asesoría al respecto, si quieres puedo contactarlos y preguntar 🙈

Por otro lado, les cuento una mini historia: Hace dos días estaba en el Metro y entró en chico invidente con una chica y se hicieron al lado mío. Ellos comenzaron a hablar, al parecer acababan de conocerse y bueno, yo no tenía audífonos puestos e iba sola así que, escuché su conversación 😳  Ella le preguntó a él que a qué se dedicaba y él le respondió "yo trabajo en Sistemas, trabajo en seguridad informática y a veces me toca arreglar unos chicharrones que ni te imaginas". La chica le respondió: "me imagino, yo no se nada de eso... y, en dónde vives ?". La verdad tenía demasiadas ganas de preguntarle a él de todo !!!! pero la prudencia me pudo más 😓  Yo no se esa chica por qué le cambió el tema preguntándole que en dónde vivía 😭  me hubiera encantado preguntarle cómo lo hace !!!! cómo aprendió !!!! cómo consiguió ese trabajo !!!! y más cosas... (jejeje)

En fin, siento que estas personas merecen seguir aprendiendo, merecen tener todas las herramientas necesarias y merecen ser felices con lo que hacen ! 

Perdón por exagerar en mi comentario, pero en lo que pueda colaborar, con mucho gusto ! 💜 

Link Guía Cultural UdeA: https://goo.gl/mF7DpE
Link UdeA "Servicio para personas con discapacidad visual": https://goo.gl/J3sIqV 

Gracias por leer 👓

**Comment by jdjuan** [comment]
@teffcode ! Wow! 😮 Yo también le hubiera preguntado cómo lo hace! 😄 Qué curiosidad 🐈 !

¡Qué buenos recursos! 👍  me parece un buen lugar para comenzar ¿Qué tal si nos das una mano? ¿Conoces a alguien allí? Tal vez nos podamos poner en contacto con ellos para que nos den una asesoría sobre cómo podríamos proceder al rededor de esta iniciativa. 💡 

Gracias por animarte! 🥇

**Comment by teffcode** [comment]
Con gusto @jdjuan ! Iré preguntando con algunos contactos y apenas consiga una respuesta te voy comentando. ✌🏼

**Comment by jdjuan** [comment]
¡Éste es ahora un proyecto oficial de la comunidad! ❤️️❤️️❤️️ ¡Gracias @teffcode!

Aquí pueden conocer el resto: [**PROYECTOS DE LA COMUNIDAD**](https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md)

**Comment by MelinaMejia95** [comment]
Hola @jdjuan y @teffcode ! :blush:

Creo que es una hermosa idea darle inclusión a estas personas a la comunidad :sparkling_heart: 
Tengo agunas ideas:

- Toda la información que se envíe de la comunidad también esté en un formato de audio, por ejemplo, la invitación a las reuniones, que en un audio se explique muy claro los temas a tratar, el lugar, la hora; también para los boletines o demás correos que se envíen, de manera que esta información también sea accesible para ellos. 
- Hacer de las charlas lo más claras posibles sin depender mucho de imágenes o texto.
- En el caso de los talleres, creo que sería ideal que contaran con un apoyo más personalizado (un tutor), alguien que se encuentre a su lado explicándoles con más detalle qué se está haciendo. Creo que esta es la parte más difícil y se deben buscar más formas de hacerlo.
- Hacer inclusión para personas con discapacidad auditiva también, y así no hayan restricciones para entrar a esta linda comunidad! :gem:

Ofrezco todo mi apoyo en caso de que alguna de estas ideas o cualquier otra sea aprobada, estoy dispuesta a colaborar en lo que se necesite! :raising_hand:

**Comment by teffcode** [comment]
Meliiiii <3 Qué rico que te unassss !!!! @jdjuan y yo tenemos algunas ideas y andamos contactandonos con personas especializadas en el tema para que nos asesoren !!!! debemos ponerte al tanto con esto también...

**Comment by jdjuan** [comment]
@MelinaMejia95 ! Súper! ❤️ Gracias por unirte a este proyecto! Tus ideas están geniales! 🏅 me gustan mucho!

Acabo agregarte al canal de comunicación de este proyecto en Gitter, ahí te hice una propuesta 🙆
