### ISSUE TITLE
Tema: Cómo desplegar aplicaciones de Angular

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#27]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Tal vez algunos de nosotros sabemos cómo crear aplicaciones de Angular, pero el verdadero valor de crear productos está en poderlos compartir con los demás. En este workshop me gustaría que alguien nos explicara cómo publicar una aplicación de Angular, bien sea en GitHub pages, Heroku, Azure, o cualquier otro.

¿Les gustaría que lo hagamos? 👍

**Comment by mafesernaarboleda** [comment]
@jdjuan me postulo para dar el taller, que requieres de mi parte!! gracias

**Comment by jdjuan** [comment]
@mafesernaarboleda Así es! 🥇 Gracias por tu entusiasmo! 😄 Yo estaré muy contento de participar de tu charla.

Es muy sencillo, para empezar solo basta con que nos cuentes con un poco de detalle cómo orientarías tu charla. Lo puedes hacer al estilo de @SantiagoMolinaOrozco en #23 👍 

Después de aprobado, anunciamos tu charla y le ponemos una fecha 📅 

P.S: Si lo haces antes del próximo Meetup, podemos hacer el anuncio allí para que tengas una audiencia más grande 😏

**Comment by jdjuan** [comment]
@mafesernaarboleda acabo de subir unas recomendaciones para los speakers de Angular Medellín, échale un ojo! 👀  

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**

**Comment by jdjuan** [comment]
@mafesernaarboleda ! ¿Cómo vas con tu charla? 👀 😁

**Comment by jdjuan** [comment]
Cerrado por #45 👌
