### ISSUE TITLE
Gist para los recursos compartidos en los eventos

### ISSUE THREAD

**Issue by khriztianmoreno** [angular-medellin/meetup#3]
# Me gustaría proponer una mejora

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

En todos los meetups siempre los speakers o realizan una presentación o tiene un repositorio de codigo donde esta el ejercicio con el cual se trabajo, entonces mi propuesta seria tener un espacio centralizado donde este el material usado por ellos y que sea de facil localización para ayudar a las personas a tener este material.

Mi propuesta inicialmente seria utilizar [Gist](https://gist.github.com/) donde cada evento tenga sus referencia, como una especie de plantilla:

**[Charla] Hablemos de Angular**
- Diego Coy:  [Slides](http://slides.com)
- Pepito: [GitHub Project](http://github.com)

**Comment by jdjuan** [comment]
@khriztianmoreno ! Buenísima propuesta, yo olvidé mencionarlo en el meetup 😳pero en este repositorio tenemos un espacio para referenciar esta información.

Tenemos una carpeta que se llama [Meetups ](https://github.com/angular-medellin/meetup/tree/master/meetups/) y allí puedes ver todos los meetups que hemos hecho, los speakers, su contenido y los hipervínculos a los slides. El del meetup pasado se encuentra **[aquí.](https://github.com/angular-medellin/meetup/tree/master/meetups/1-hablemos-de-angular-en-medellin)**

¿Qué opinas?

**Comment by khriztianmoreno** [comment]
@jdjuan Apenas es, me gusta, super organizado, ojala siga asi. Excelente.
