### ISSUE TITLE
Dar feedback por medio de email a los que se registran en el formulario de los meetup

### ISSUE THREAD

**Issue by Shinkei** [angular-medellin/meetup#30]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [x] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [x] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Estaría muy bien, que a las personas que se registren en el formulario para los meetups les llegara un email confirmando el registro, ademas se podría dar mas información o noticias en este email, sin generar spam.

Ya que se usa un formulario de google, se podría usar google scripts para este propósito.
[google scripts](https://www.google.com/script/start/)

**Comment by jdjuan** [comment]
@Shinkei gracias por proponer esta mejora! 🏅 

Creo que ésta es una oportunidad precisamente para hacer una aplicación en Angular 🅰️ , no crees?
Podríamos hacerlo un proyecto de la comunidad y que las personas participen de la creación a través de GitHub.

¿A quién le gustaría participar? 😃

**Comment by danielcb29** [comment]
@Shinkei @jdjuan me apunto!, excelente

**Comment by Shinkei** [comment]
Claro @jdjuan cuenta conmigo

**Comment by jdjuan** [comment]
@Shinkei @danielcb29 ! Gracias por participar! 😁 Su primera misión es hacer una lista de los hitos para llevarlo a cabo. 

¿Qué se les viene a la cabeza? 🤔 ¿Qué tareas son necesarias para hacer este formulario? 🤔 ¿Cuál creen que debería ser el alcance si lo consideramos un MVP(producto mínimo viable)? 🤔

**Comment by danielcb29** [comment]
@jdjuan @Shinkei Yo consideraría importante que nuestra app pudierá: 

_ Guardar la información basica de un evento
- Enlazar eventos con un formulario (siempre será el mismo formulario o seran dinamico?) 
- Mostrar la información general del evento dentro del formulario y permitir llenar los campos ingresando su correo electronico en primera instancia (para no tener entradas repetidas) 
- Permitir editar tu entrada de un evento (que aun este abierto)
- Abrir o cerrar la disponibilidad de un formalario enlazado a un evento. (si se pueden programar fechas de apertura y cierre estaría genial, sin embargo, para el MVP podríamos dejarlo manual) 

He leido en #34 ideas para crear un blog, que opción habría de integrar estas herramientas? 

Por ultimo, respecto al diseño considero que podriamos hablar con nuestro actuales (o futuros 🍺 ) patrocinadores para comprar una plantilla y ahorrarnos un poco de trabajo en eso.

**Comment by alejandronanez** [comment]
Qué buenas ideas!
Para hacerle seguimiento a los mails, podríamos usar un servicio como Mail chimp tal vez (ellos tiene api).
O tal vez....usar la API de Meeetup.com a ver qué tiene disponible

**Comment by Shinkei** [comment]
Por ahora enfoquemonos en el formulario, yo pensaría:
- formulario para que el usuario ingrese los datos
- guardar información del usuario (firebase - documento de google)
- enviar email de confirmación al usuario
- habilitar y deshabilitar el ingreso de información desde una bandera (puede ser en firebase)(admin)

Ya después iríamos agregando e integrando mas funcionalidades.

**Comment by alejandronanez** [comment]
Ohhh entiendo, estaba viendo el problema desde otro ángulo. Suena bien @shinkei

**Comment by Shinkei** [comment]
Bueno muchachos, entonces si les parece ire creando un repo con un proyecto base en angular-cli (aplicando lo que aprendimos en el meetup pasado) :smile:

**Comment by alejandronanez** [comment]
@jdjuan te parece crear un repo dentro de `angular-medellin` y ponerle unas restricciones para los merge/branches/etc... para evitar catástrofes?

**Comment by danielcb29** [comment]
@Shinkei Excelente. @alejandronanez Creo que podríamos trabajar siguiendo el git flow y trabajar cada uno dentro de su propio fork haciendo PR a origin cuando se tenga una nueva funcionalidad o solución a bug y reservar origin para integración, testing y despliegue. No se que opinan? Por otro lado si sería muy chevere que origin quedara dentro de angular-medellin 😀

**Comment by alejandronanez** [comment]
@danielcb29 claro, de una! 👍 💯

**Comment by jdjuan** [comment]
@Shinkei @danielcb29 @alejandronanez acabo de crear el repositorio dentro de Angular Medellín para trabajar sobre este proyecto! 🎉 🎉 🎉 !

Gracias por todas sus contribuciones, ¡vamos a hacer un excelente trabajo! 👍 
Propongo que definamos el alcance del proyecto a través de un hangout, en el que como resultado obtengamos un **roadmap** de las funcionalidades a desarrollar, y un **documento técnico** de las tecnologías que vayamos a utilizar.
Una vez esto esté definido empezar a trabajar, ¿les parece? 🙂 

Ustedes 3 y (cualquier otro miembro que quiera participar 👍 ), dejen un comentario con su cuenta de correo de gmail, y yo me encargo de crear un chat para coordinar el hangout 🔥

**Comment by alejandronanez** [comment]
Y qué tal si usamos gitter? #justSaying 😏

**Comment by jdjuan** [comment]
Touché! 😌 Ya creé el canal! Ahí coordinamos! 👍

**Comment by jdjuan** [comment]
¡Éste es ahora un proyecto oficial de la comunidad! ❤️️❤️️❤️️ ¡Gracias!

Aquí pueden conocer el resto: [**PROYECTOS DE LA COMUNIDAD**](https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md)

**Comment by alvaromartinez986** [comment]
Estoy interesado  en participar @danielcb29 , @jdjuan me podrias agregar al proyecto?

**Comment by Shinkei** [comment]
Hola, al fin cuando vamos a reunirnos por hangout o gitter? por ahora cree un repositorio para el proyecto en este (repo)[https://github.com/Shinkei/formulario-angular-medellin].

**Comment by jdjuan** [comment]
@Shinkei ! asegúrate de revisar el Gitter 😛 ahí tenemos un canal de comunicación al respecto! Nos vemos el meetup de React para hablar del tema https://www.meetup.com/React-Medellin/events/240587795/

**Comment by anibalortegap** [comment]
Buenas noches @jdjuan  aun hay cupo para participar en el proyecto ?

**Comment by jdjuan** [comment]
Hooola @anibalortegap claro que sí! Te voy a agregar al grupo en Gitter! Allí discutimos el trabajo, no olvides escribir presentándote! 👍

**Comment by jdjuan** [comment]
Actualmente Google Forms ya permite reenviar feedback de la respuesta al registrarse. Usaremos ésa de ahora en adelante! 👍
