### ISSUE TITLE
Publiquemos el temario de los meet up's 

### ISSUE THREAD

**Issue by brianou7** [angular-medellin/meetup#32]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [x] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Les parece si publicamos el temario de los meet up's con tiempo y así podemos ir un poco preparados al meet up, o por lo menos leer de que se trata para aprovechar más el tiempo!

¿Que opinan?

**Comment by teffcode** [comment]
Hola @brianou7 !

Te refieres a un temario que abarque cuánto tiempo ? 

La verdad, creo que sería un tanto complejo porque como decía @jdjuan en el meetup de ayer, van a llevar invitados de otras partes y adicionalmente, la comunidad también puede proponer los temas !

😃

**Comment by brianou7** [comment]
Hola @teffcode!

Es cierto que puede ser un poco dificultuso en un comienzo, pude ser algo básico en principio (para empezar), la idea es tener algo minimamente estructurado con el fin de que podamos sacar un mejor provecho de las reuniones, solo digo que si nos organizamos un poco y podemos saber de antemano hariamos de los meet up's algo un poco más fructífero, y si bien la comunidad puede proponer los temas, estos deben conllevar una minima preparación para hacerlo bien.

Pudriamos empezar solo con un listado minimamente detallado de todos los temas a abordar en el meet up, y luego, pues ya mirariamos, no?

Saludos :smile:

**Comment by teffcode** [comment]
😱  siiii, es cierto ! sería super 👏🏼

**Comment by jdjuan** [comment]
@teffcode ¡Gracias por participar! 😄 

@brianou7 ¡Me gusta tu idea! 😀 Si hacemos eso los asistentes podrían estudiar el tema de antemano y estarían más preparados para la charla aprovechando mucho más el meetup 🔥 

¡No se diga más!, de ahora en adelante agregaremos recursos (opcionales) para leer antes de cada cada meetup 👍 ¡Buena esa!
