### ISSUE TITLE
🎥  Grabar los meetups ! 

### ISSUE THREAD

**Issue by teffcode** [angular-medellin/meetup#33]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [x] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Hola ! 

Me encantaría que grabaran los meetups 🎬  Así podríamos retroalimentarnos y permitir a los que no puedan asistir que no se pierdan ni un solo instante de lo que sucede en la comunidad 😃

**Comment by jdjuan** [comment]
@teffcode ¡Buena esa! 🥇 Totalmente de acuerdo contigo, grabar los meetups permitiría ver los contenidos a las personas que puedan asistir a los meetups! Además sería bonito tener las memorias 😊 

¡Sin embargo necesitamos ayuda! Personalmente no tengo mucha experiencia con este tipo de software. Sé que existe Camtasia y sé que MedellínJS utilizar OBS. Pero la verdad no sé cuál sería la mejor opción (gratuita) para lograrlo 😅 

¿Alguna idea? ¿Alguien que sepa de estos temas y nos de una mano?

**Comment by juancapm09** [comment]
Hola @teffcode, @jdjuan y toda la comunidad..
 
La verdad no se del tema tampoco, pero se me ocurría hacer un live streaming usando youtube. Para lo cual necesitaríamos crear una cuenta y tener un administrador de dicha cuenta (Ya que para hacer streaming hay que validar la cuenta via mensaje de texto o llamada).

- Googlee un poco y encontré un [tutorial](https://support.google.com/youtube/answer/2474026?hl=es&ref_topic=6136989) para hacer la configuración. 
- Uno de los pasos es elegir el codificador de emisión, ellos dan una lista, entre los cuales esta OBS. 
- Lo descargue y me pareció bastante intuitivo y fácil de usar, rápidamente pude configurarlo y hacer un live streaming. Basicamente, según entendí hay q definir escenas en las que uno agrega lo q quiere transmitir, audio, video o pantalla, etc.
- En youtube desde le panel de control puedes manejar y revisar todo; como espectadores, chat, el link de transmisión y el key para crear la transmisión.
- Una vez terminas la transmisión el video se sube automáticamente a youtube y listo.

Saludos,

**Comment by brianou7** [comment]
Me parece genial la idea de @juancapm09 ... al igual que @jdjuan no se mucho del tema, pero me hace ilusión la idea, si puedo ayudar, cuenten conmigo.

**Comment by jdjuan** [comment]
@brianou7 gracias por darnos una mano! 😄 

@juancapm09 ! Qué buenos datos! 🥇 👍 😁 

Excelente, realmente no parece ser tannnn complicado 🙂 Voy a crear la cuenta de la comunidad y trataré de seguir el tutorial. Si tengo alguna duda te pregunto. Lo que también podemos hacer es que en nuestro próximo meetup nos encontremos antes de empezar para dejar todo listo. ¿Me darías una mano? 😁

**Comment by teffcode** [comment]
Súpeeeer !!!! Gracias @juancapm09, @brianou7 y @jdjuan :3

**Comment by juancapm09** [comment]
@jdjuan Si claro me confirmas y podemos hacer el experimento en el proximo meet up! 👍😄

**Comment by jdjuan** [comment]
@juancapm09 listo! Te escribo por Gitter! 👍 😁  https://gitter.im/angular-medellin
