### ISSUE TITLE
Blog por y para la comunidad 👩🏻‍💻 👨🏼‍💻

### ISSUE THREAD

**Issue by teffcode** [angular-medellin/meetup#34]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [x] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción

Hola ! 

Para poder crecer entre todos, sería genial crear un blog entre toda la comunidad para aportar temas y conocimientos... o bueno, una app también ! donde podamos, entre otras cosas, subir videitos con aportes (tutoriales) y hasta un top de los más participativos e influyentes ⭐️

**Comment by alejandronanez** [comment]
💯💯💯💯

**Comment by MelinaMejia95** [comment]
Apoyo la idea! Me parece excelente!

**Comment by alejandronanez** [comment]
Súper!
@jdjuan qué te parece aprovechar "Github pages" y tener algo como https://angular-medellin.github.io/ 💯

**Comment by jdjuan** [comment]
🎉 🎉 🎉 ¡wow wow wow! 🎉 🎉 🎉 

Podríamos utilizar GitHub pages (@alejandronanez) para subir un blog o una aplicación en la que los miembros puedan participar subiendo contenidos y recursos (@teffcode). Luego, con base en su participación podríamos seleccionar quiénes participan del **VIP Workshop**! 🔥 🔥 🔥 

¡Buenísima idea! 🥇 

Gracias por proponerla, aportes como éste le dan un impulso tremendo a la comunidad! ❤️ 

Con el fin de poder llevar esto a cabo necesitamos listar los hitos que tenemos hasta ahora y articularlos para que los esfuerzos vayan en la misma dirección 🗺 
Propongo que los empecemos a desarrollar en este orden. ¿Qué opinan? 😺 

- [ ]  Hacer el boletín quincenal de la comunidad #16
- [ ]  Hacer el landing page de la comunidad en GitHub pages
- [ ]  Hacer la app donde los miembros puedan participar

**Comment by alejandronanez** [comment]
@jdjuan súper ese orden de ideas,
Sabes de alguien que pueda colaborarnos con el diseño?

 Pregunta...
> Hacer la app donde los miembros puedan participar

Para publicar en github pages creo que basta con crear un pull request con el nuevo contenido 👍  o te refieres a la app que mencionamos en #38 ?

**Comment by jdjuan** [comment]
@alejandronanez buena inquietud!
¿Alguien en la comunidad que sea diseñador web o tenga conocimientos!? 🤔 

- Me refería a la idea original de @teffcode en la que los miembros pueden subir contenidos, comentar y publicar recursos 🙂

**Comment by jdjuan** [comment]
¡Éste es ahora un proyecto oficial de la comunidad! ❤️️❤️️❤️️ ¡Gracias @teffcode @MelinaMejia95 @alejandronanez !

Aquí pueden conocer el resto: [**PROYECTOS DE LA COMUNIDAD**](https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md)

**Comment by cardotrejos** [comment]
Bueno por acá mi aporte, podemos hacer un landing sencillo y ahí poner el campo para que se suscriban al boletín, para el boletín podemos utilizar Mailchimp u otro proveedor de email marketing. Si quieren puedo ir mirando lo del landing, para ser coherentes utilizar Angular. Espero sugerencias frente a esto para empezar a darle. :muscle:

**Comment by jdjuan** [comment]
@cardotrejos ! Buenísima idea, creo que podríamos utilizar templates gratuitos para lograrlo no? 🤔 
Y Mailchimp me parece una buena opción gratuita, yo la he utilizado y es 👌 

Actualmente no hay nadie trabajando sobre este proyecto, ¿te gustaría darle inicio?

**Comment by alejandronanez** [comment]
Pregunta, vamos a crear un blog from scratch?

**Comment by cardotrejos** [comment]
@jdjuan Tenes alguna sugerencia de template? Para que miremos alguno y vayamos escogiendo.
@alejandronanez Que sugieres? A ver como estructuramos el proyecto del blog. Pero yo pensaría que por ahora para el landing, solo el landing plano con el campo de suscripción.

**Comment by jdjuan** [comment]
@alejandronanez @cardotrejos ! 👍 buenas sugerencias 👍 
No quiero perderlas de vista, qué tal si nos concentramos en el proyecto del Newsletter y luego consideramos el Blog?

Así que lo que podemos hacer es seguir la conversación del Newletter en #16 ? Qué tal? 😁 

![screenshot-github com-2017-06-13-17-44-20](https://user-images.githubusercontent.com/3171900/27107945-69dc7640-5060-11e7-9985-d40a472b4e9b.png)

**Comment by alejandronanez** [comment]
Para el blog me parece suficiente agarrar algo que ya existe, no tiene que ser un proyecto en Angular. Por ejemplo podemos escribir en Medium o utilizar ghub pages (Jekyll). That's my $0.02

**Comment by cardotrejos** [comment]
@alejandronanez Concuerdo contigo en lo del blog, yo decía era angular para la landing, algo meramente informativo con el campo para la suscripción al boletín. Pero para el blog si utilicemos algo que ya existe, como tu dices Medium puede ser una excelente opción. @jdjuan Y si migremos a newsletter saquemos eso primero.

**Comment by jdjuan** [comment]
@alejandronanez @cardotrejos ! Buenísima discusión. Totalmente de acuerdo, aprovechemos los recursos que tenemos a disposición como Medium 👌 

Creo que podemos darle 400 puntos 🏅 al que se anime a escribir un artículo para la comunidad 😁 (que luego puede ser compartido en el boletín con el resto de la comunidad). Me gusta que las ideas se estén entrelazando, los esfuerzos articulados logran más 👌

**Comment by pablovem** [comment]
✋  [Blog](https://medium.com/angularmedellin).

**Comment by jdjuan** [comment]
Gracias @pablovem ! https://medium.com/angularmedellin/

FYI: @teffcode @cardotrejos @alejandronanez
