### ISSUE TITLE
Directivas en Angular

### ISSUE THREAD

**Issue by camilo56** [angular-medellin/meetup#35]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [x] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Me gustaría compartir con la comunidad cuales son las directivas mas utilizadas en angular y lo que se puede hacer con ellas.

**Comment by alejandronanez** [comment]
Qué cool Camilo! ✌🏼🚀

**Comment by CrisDan1905** [comment]
Me parece genial. Hay un monton de tipos de directivas y seria muy bueno que pudieras hablar de ellas. Me llamo particularmente la atención un tipo que vi hace poco que son las directivas de validacion. Son bastante geniales, y potentes. Ojala pudieras hablar de ellas :smile:

**Comment by jdjuan** [comment]
@camilo56 maravillosa esta charla! 👍 💡 

¡Bien pensada! Gracias por contribuir y querer ser speaker 😎 

El siguiente paso es sencillo, sólo échale un ojo 👀 a nuestras directrices para la saques del estadio en presentación:

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**

**Comment by jdjuan** [comment]
Cómo va esa presentación @camilo56 ! 👀 Recuerda leer los guidelines y contarnos un poco de ti! 🌵

**Comment by jdjuan** [comment]
@camilo56 
![1rz4fs](https://user-images.githubusercontent.com/3171900/27840250-1619d422-60bd-11e7-97cf-641d18b5c9eb.jpg)

**Comment by camilo56** [comment]
Hola, la envió a un correo especifico o la comparto por este medio?

**Comment by jdjuan** [comment]
@camilo56 ya recibí tus diapositivas, mira el email 😁

**Comment by camilo56** [comment]
ok, gracias
