### ISSUE TITLE
Charla en inglés sobre cómo mejorar las habilidades del idioma.

### ISSUE THREAD

**Issue by MelinaMejia95** [angular-medellin/meetup#36]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [x] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

Hola! :bowtie:
En el meetup pasado @jdjuan mencionó que sería ideal en cada reunión hacer un espacio de 15 minutos para hablar y poner en práctica el inglés, así que me gustaría dar una pequeña charla en ese espacio.

La charla incluiría:
- Mi experiencia con el idioma y cómo he logrado perfeccionarlo :raising_hand:
- Técnicas para mejorar las habilidades del inglés :key:
- Lugares para compartir y poner el idioma en práctica :house:

Para animarlos a todos y crear hábitos de aprendizaje del idioma! :tada: :confetti_ball:

**Comment by teffcode** [comment]
Súper !!! Love it 💕

**Comment by jdjuan** [comment]
@MelinaMejia95  Woohoo! 🎉 Buenísima! Creo que esta sería nuestra primera charla no técnica, y lo estábamos esperando! 😁 

👍 Tienes luz verde para preparar los Slides! Échale un ojo 👀 a la guía de los speakers:

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**

**Comment by MelinaMejia95** [comment]
Listo! :punch: 

Prepararé unos super Slides! @jdjuan Cuando los tenga listos te los mando para que les des el visto bueno! :computer:

\ :grin: /

**Comment by brianou7** [comment]
Hola @MelinaMejia95, ya que tú propusiste este tema, y dite la charla del mismo, que opinas de crear un chat (en cualquier medio) dónde hablemos de temas de la comunidad, pero únicamente en inglés para que quienes queramos prácticar el idioma lo podamos hacer y tengamos ese apoyo de personas como tú que conoces.

@MelinaMejia95 que dices?

**Comment by alejandronanez** [comment]
@jdjuan tú puedes crear el canal en gitter. 👍

**Comment by MelinaMejia95** [comment]
@brianou7 Sii! Que súper genial idea! 😄 
Podríamos crear el canal en Gitter, o incluso en Slack! @jdjuan Qué opinas?

**Comment by jdjuan** [comment]
@MelinaMejia95 @brianou7 @alejandronanez me parece una idea buenísima! Ya mismo creo el canal. Por ahora lo podemos hacer en Gitter que ya tenemos varias personas allí, y si luego vemos la necesidad consideramos Slack! 😁

**Comment by jdjuan** [comment]
# [English Only Channel](https://gitter.im/angular-medellin/english-only?source=orgpage) 👍
