### ISSUE TITLE
Hablemos de graphql y aplicado en angular2 

### ISSUE THREAD

**Issue by H4isan** [angular-medellin/meetup#37]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ x] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [x ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
GraphQL es un protocolo agnóstico y no depende en nada de HTTP. No usa métodos o respuestas HTTP. Por supuesto, sigue siendo el canal más popular para comunicarse entre consumidores de GraphQL. 
GraphQL dispone de un sistema de tipado fuerte por el que cualquier mal uso puede ser rápidamente detectado en tiempo de desarrollo y  la API puede ser single endpoint que ademas nos permite gestionar que informacion queremos que nos llegue, asi evitando informacion extra que en redes mobile son las q soportan este peso.

**Comment by alejandronanez** [comment]
Genial ese tema. ❤️ GraphQL ❤️

**Comment by jdjuan** [comment]
@H4isan buenísimo ese tema ❤️ hace rato quería echarle un ojo a esto. Gracias por proponerlo 👍 🥇 

Échale un ojo a nuestras recomendaciones para los speakers de Angular Medellín 👀 y cuéntanos un poco de ti

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**

**Comment by H4isan** [comment]
Hola soy harlen, tengo 20 año junior  💃.
Un poco acerca de mi pues... fui freelance desde los 18, trabajando en Front-End con Jquery, Javascript, ajax, Css y Sass. En la parte de BackEnd con php, Ruby On Rails y manejando motores de bases de datos. Actualmente Estoy trabajando en Yuxi Global como Desarrollador Front-End pero a todo me le mido 😄  y tengo el placer de presentar este Tema GraphQL, ya que me parece fascinante la nueva visión que hay para las apis liderada por Facebook.
Los temas que planeo mencionar son:
°Un poco acerca de GraphQl
°Queries & mutaciones
°Ventajas que hay de usar GraphQl Vs Rest full
°Como implementar GraphQl en Angular2
°Demostración en vivo de GraphQl con Angular2

**Comment by jdjuan** [comment]
Súper bien Harlen! Hazme llegar tus slides por correo para una retroalimentación final y luego quedamos listos para anunciar tu charla 🤙 🤙 🤙
