### ISSUE TITLE
Mini Proyectos!!!

### ISSUE THREAD

**Issue by alejandronanez** [angular-medellin/meetup#38]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [x] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [x] **Otro**

## Descripción
Me he dado cuenta que hay mucha gente con ganas de llevar su aprendizaje a un nivel más 'práctico', propongo que realicemos un mini proyecto - sin muchisima complejidad para que sea realizable en un corto plazo. Tal vez, organizar un hangout, tocar los temas que quisieran aprender, crea un repo dentro de la organización de Angular Medellín y empezar a trabajar, yo ando un poco corto de tiempo como para escribir la aplicación pero sí tengo tiempo para ayudar a levantar requerimientos, resolver dudas y hacer code reviews. Qué opinan? @jdjuan qué te parece lo de crear un repo dentro de angular-medellín para este fin o qué approach te parece?

Quedo pendiente!!!

**Comment by CrisDan1905** [comment]
Me parece muy buena idea. La apoyo 100%

**Comment by teffcode** [comment]
Siiiiii... Súper !

**Comment by Estoja** [comment]
Me parece una excelente idea.  Tengo una propuesta sobre un proyecto de tres partes que podríamos resolver entre todos.

**Comment by brianou7** [comment]
Eso suena genial!

**Comment by wdospinal** [comment]
Un proyecto open source, bien organizado de una 🗡

**Comment by alejandronanez** [comment]
Me suena mucho un proyecto open source como dice @wdospinal. Tal vez podríamos identificar un problema e intentar resolverlo usando Angular.

**Comment by jdjuan** [comment]
@alejandronanez excelente! 🥇 🥇 🥇 

Así podríamos poner en práctica nuestras habilidades un proyecto real y a la vez sería el primer acercamiento al mundo open source 😁 ¡Qué buena idea!

Podríamos empezar con algo simple y luego incrementalmente podemos hacerlo mejor! 😃 
De hecho, **¿Qué tal si pogramáramos una especie de Hackathon para hacerlo durante todo un día?** 🔥 🔥 🔥 

Yo podría conseguir la pizza 😏 😏 😏

**Comment by alejandronanez** [comment]
I'm down.

**Comment by MelinaMejia95** [comment]
@jdjuan Yo me apunto! :flushed:

**Comment by danielcb29** [comment]
Hackaton time! excelente @jdjuan me apunto. Dentro de mi universidad (Univalle) hay varios problemillas que proyectos open source podrían solucionar... solo digo 😁. Con un compa de Cali estamos hablando para hacer una pequeña app para la reserva de cupos dentro del escuela de Ingeniería de Sistemas y Computación. @alvaromartinez986

**Comment by JuanEstebanYC** [comment]
De una! excelente idea la de @jdjuan , y sobre lo que comenta @danielcb29 sería bueno que se armara un grupo para realizar un par de aplicativos y que de parte de la comunidad Angular Medellin se pudiera ofrecer soluciones Open Source que le sirvan a cualquier persona.

**Comment by teffcode** [comment]
Me encanta lo de la problemática que propone @alejandronanez ! Y lo de la Hackathon propuesta por @jdjuan también ! 

Lo que sí pienso, es que para la Hackathon sería bueno que tuvieramos unos conocimientos previos como comunidad ! 👩🏻‍💻 👨🏼‍💻  

Aunque, ustedes son los que saben !!! entonces, lo que propongan estaría muy bien 😃

**Comment by alejandronanez** [comment]
Para cuándo un hangout con los interesados para discutir qué problematica resolver y arrancamos de ahí. 🤘🏼

**Comment by CrisDan1905** [comment]
me parece muy buena idea la del hackathon. Me apunto!

**Comment by teffcode** [comment]
Me apunto para el Hangout @alejandronanez 💻 💚

**Comment by alvaromartinez986** [comment]
Me parecería muy bien organizar el Hangout, el día 27 de Junio a las 8 pm, para hablar acerca de la app de reservas de cupos para la Escuela de Ingeniería de Sistemas y Computación, planteado por @danielcb29,  de la Universidad del Valle.

**Comment by cardotrejos** [comment]
Me apunto!

**Comment by oscardmg** [comment]
Yo me apunto

**Comment by JamesChe91** [comment]
Me apunto

**Comment by Estoja** [comment]
Me apunto

**Comment by alejandronanez** [comment]
Cómo van las cosas, ya _tendríamos_ dos proyectos, este y #30, qué les parece si arrancamos por algo pequeño mientras tanto (sin descartar algo grande como lo que se ha hablado acá)

**Comment by jdjuan** [comment]
😲 😲 😲 ¡Vaya! Éste es el issue con más actividad en la historia de la comunidad 😝 👍 👍 

¡Gracias a todos por su entusiasmo y ganas de participar! 🥇 Me enorgullece contarles que Angular Medellín ya cuenta con **5 proyectos**, y al parecer se vienen muchos más! Es por esto que hemos decidido crear **la lista oficial de proyectos**.

Allí pueden conocer **qué** proyectos existen, **cuáles** están activos, **quiénes** están participando y **cómo** pueden unirse. A partir de este momento, todos los miembros pueden proponer proyectos para desarrollar dentro de la comunidad! ❤️️❤️️❤️️

Conózcanlo aquí: [**PROYECTOS DE LA COMUNIDAD**](https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md)

PD: @danielcb29 y @alvaromartinez986 creen un issue con la descripción del proyecto y luego lo agregamos a la lista también 😉

**Comment by pablovem** [comment]
Aún puedo sumarme a este proyecto? 😄

**Comment by oscardmg** [comment]
En los miniproyectos me parece que seria muy bueno lograr crear un dashboard desde 0 al estilo de este: 

https://genesisui.com/demo/?theme=genius&version=angular4

que les parece la idea?

**Comment by alejandronanez** [comment]
@pablovem claro, esto es open source! Todos pueden ayudar

**Comment by jdjuan** [comment]
@pablovem ! Claro! Échale un ojo a esta página y dinos en qué proyecto quieres colaborar, o si se te ocurre otro?  https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md 😁

**Comment by jdjuan** [comment]
@oscardmg ! Ese reto se ve interesantísimo! Por lo que veo ya está hecho para Angular, así que como un ejercicio personal me parece súper válido. Por ahora en la comunidad no necesitamos un Dashboard pero tal vez en una próxima iteración sí. Si se te ocurre algo más mientras tanto déjanos saber! 😀

**Comment by jdjuan** [comment]
@alejandronanez ahora te puedes dar cuenta que tu iniciativa se convirtió en los [Community Projects](https://github.com/angular-medellin/meetup/blob/master/COMMUNITY-PROJECTS.md). Muchas gracias por proponerlo, la gente está animadísima a participar! 👍
