### ISSUE TITLE
Autenticación y Autorización con directorio activo

### ISSUE THREAD

**Issue by oscardmg** [angular-medellin/meetup#41]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **🔥 Ser el próximo speaker:** Escribe los detalles de tu charla
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Proponer una mejora a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [x] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
Saludos! Quien podría ayudarme por favor. Necesito implementar autenticación y autorización en angular conectándome a un directorio activo. Alguien que me pueda compartir información o darme una mano por favor.

**Comment by alejandronanez** [comment]
Hola Óscar, hmmm.... **nunca** he trabajado con Directorio Activo, pero un par de preguntas para entender un poco la situación...
- Directorio Activo (tu backend) te permite usar una API REST/GraphQL que envíe JSON desde/hacia tu aplicación de Angular?
- Estás utilizando un state manager como [ngrx/store](https://github.com/ngrx/store)
- En general, cómo funciona la autenticación con Directorio Activo? Usan JWT?

**Comment by oscardmg** [comment]
Hola Alejandro!

Apenas voy  a empezar, actualmente la intranet la tengo creada en php ya en php tengo la autenticacion contra el directorio activo, la idea seria  crear una API REST. 

todavia no  he manejado state manager, apenas estoy empezando :) entonces la idea es ver de donde empezar. 

muchas gracias.

**Comment by alejandronanez** [comment]
Ok!
Óscar, cuando las aplicaciones empiezan a crecer es bueno considerar un state manager, te va a ahorrar muchísimos dolores de cabeza, te recomiendo ver los tutoriales que hay en [EggHead]https//egghead.iol) hay mucho contenido de Angular 1 / 2 y desarrollo web en general!

**Comment by oscardmg** [comment]
Voy a seguir este tutorial:

https://egghead.io/courses/angularjs-authentication-with-jwt

**Comment by jdjuan** [comment]
@oscardmg ! Gracias por tu pregunta! 👍 

Yo también seguiría la recomendación de @alejandronanez utilizando una API REST para conectar tu aplicación de Angular 👍 Creo que ése sería el primer paso para poder hacerlo.

Dentro de la comunidad hay un sensei del Directorio Activo. Le convocaré a este thread para que te de una respuesta.

> Voy a seguir este tutorial:
https://egghead.io/courses/angularjs-authentication-with-jwt

Cuídado! ⚠️ Ése parece ser AngularJS. Diferente de Angular  ☣️

**Comment by JuanEstebanYC** [comment]
Llegando un poco tarde a la conversación, totalmente de acuerdo con @alejandronanez cuando dice que es posible hacer el acceso al AD desde el back end y se consume por medio de Web API. Por ejemplo, en la compañía donde actualmente trabajo se tiene algo similar donde con APS.NET Web API se expuso un servicio donde, entre otros, se consulta el AD y con JS se lee el servicio y se obtiene la información requerida.

**Comment by oscardmg** [comment]
Muchas gracias a todos! 

Voy a inventar mas sobre https://jwt.io/ y como crear  API REST en php con https://www.slimframework.com/

**Comment by alejandronanez** [comment]
@oscardmg por si acaso, he escuchado muy buenas cosas de Laravel y Lumen para trabajar en PHP.

Quedamos pendientes a ver cómo te va 🤘🏼

**Comment by pablo-diaz** [comment]
Hola Oscar:
Otra opción que puedes buscar es OpenID/OAuth, de esta manera:
- Tus usuarios siguen siendo manejados por tu AD (altas/bloqueos/bajas de usuarios), sin tenerte que preocupar por su estado en tus endpoints
- Luego lo que tienes que hacer es autorizar los llamados a los endpoints que expones al frointend (angular), que esto dependerá del lenguaje de programación de tu backend (php?). De esta manera, tus endpoints revisarán sobre la presencia del JWT (en el header Authorization (bearer) del HTTP request) otorgados por tu AD y en caso que no esté presente , el estandar OpenID lo redireccionará a la página de autenticación de tu AD, el cual, una vez correctamente autenticado el usuario, generará un JWT que el fronend deberá guardar (en memoria), para así pasarlo siempre en cada request (de ahora en adelante, hasta que haga logout) a tus endpoints, en forma de un Authorization (bearer) header. De esta manera, cuando tus endpoints detecten que sí está presente este JWT, tomará la información que viene en él y autorizará sus claims (que el usuario sea Admin, o cualquier otra info que necesites autorizar en el backend) y procederán finalmente con realizar su labor o devolver un 403 - Unauthorized en caso tal que los claims del usuario no satisfagan el filtro del endpoint

**Comment by oscardmg** [comment]
Pablo muchas gracias por las recomendaciones.
