### ISSUE TITLE
Animaciones en Angular

### ISSUE THREAD

**Issue by CarlosAngulo** [angular-medellin/meetup#44]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [x] **🔥 Ser el próximo speaker:** ¡Súper! No olvides leer nuestras recomendaciones
- [ ] **💬 Proponer un tema:** Qué te gustaría y por qué
- [ ] **👍 Sugerir una idea/proyecto a la comunidad:** ¡Vaya! ¿Qué hay que hacer?
- [ ] **👏 Dar mi retroalimentación:** ¡Gracias!, esto nos hace crecer
- [ ] **😎 Convertirme en organizador:** Explícanos por qué y cómo puedes aportar
- [ ] **🤓 Resolver una duda técnica:** No olvides mencionar tanto detalle como sea posible 
- [ ] **Otro**

## Descripción
💬 Desde hace ya varias versiones, Angular viene con soporte nativo para animaciones y transiciones gracias al módulo *animations*. En esta charla veremos los conceptos básicos de animación en la web y las ventajas de utilizar este feature sobre las ya conocidas animaciones con CSS y otras librerías conocidas. Finalmente realizaremos un ejemplo práctico que servirá como punto de partida para los proyectos en que las vayamos a incluir.

☝️ Diseñador Industrial y Front End Developer con conocimientos en UX-UI, Animación y Desarrollo de Videojuegos.

⏰ Cerca de 45 minutos.

**Comment by alejandronanez** [comment]
Qué bien @CarlosAngulo, suena súper la charla!

**Comment by jdjuan** [comment]
@CarlosAngulo ! Buenísima! Éste tema es súper 🤙 🤙 🤙 

Tienes luz verde, hazme llegar tus diapositivas para darte un Feedback final, y estaríamos listos para que subas al escenario y la saques del estadio 🏋️

**Comment by jdjuan** [comment]
@CarlosAngulo 
![1rz4fs](https://user-images.githubusercontent.com/3171900/27840222-e982c298-60bc-11e7-9615-bee33d9a43b7.jpg)

**Comment by jdjuan** [comment]
Excelente charla @CarlosAngulo ! 🥇 💯
