### ISSUE TITLE
🎥 Hagamos un video promo de la comunidad 🎥

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#47]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hoy conocí [Promo](https://slide.ly/promo) y me pareció fabuloso 😃 Crear un video promocional de la comunidad me tardó 5 minutos 😮😮😮 y se veía espectacular ~porque lo hice yo~ porque la aplicación es muy buena! 

La sorpresa fue que descargarlo costaba 40 USD 😭 

¿Qué les parece si buscamos una alternativa gratuita para crear un video promo de la comunidad? 
¿A alguien le gustaría echarnos una mano buscando cómo podemos hacerlo? 💪

**Comment by MelinaMejia95** [comment]
@jdjuan Estuve buscando herramientas para hacer el video pero la mayoría por no decir todas tienen costo, la única que encontré gratis fue PowToon, pero no creo que sea la indicada :sweat_smile: 

Estaba pensando, que tal hacer el video como un "Draw my life", podríamos conseguir a alguien con una buena cámara.

**Comment by jdjuan** [comment]
Vale vale, sigamos buscando, no conozco el de Draw my life 😆 pero tal vez alguien en la comunidad nos pueda dar una mano! 👍

**Comment by MelinaMejia95** [comment]
Mira, es algo así https://www.youtube.com/watch?v=KPmoDYayoLE !

**Comment by jdjuan** [comment]
Me gusta, también puede ser! 🤔

**Comment by cardotrejos** [comment]
Y si hacemos la vaca para descargar el que ya hiciste? 😛 . Voy con la mitad 😃

**Comment by jdjuan** [comment]
@cardotrejos ! Uyyyyyyyyyy, #presenciaYplata 😁 No es mala idea, aunque es muy costoso 40 USD mensuales es mucho dinero para el uso que le vamos a dar. Si no encontramos otra alternativa entonces consideramos pagarla! 👍

**Comment by cardotrejos** [comment]
Pues miremos alternativas, y pues si hacemos la vaca no es mucha plata, solo faltan 20 USD jajaja.  Si son 40 USD el mes podemos sacarle el jugo y hacer videos promo para este año y el otro. 😆

**Comment by Cdvalencia** [comment]
Hola, me parece que lo mejor para hacer un video, es [Adobe AfterEffects](https://www.adobe.com/la/products/aftereffects.html?sdid=KQPRU&mv=search&s_kwcid=AL!3085!3!158996232419!e!!!!adobe%20after%20effects&ef_id=WXBKoQAAAL@n0eoW:20170822223006:s). Conozco varias cosas de se programa, y creo que puede ser una buena herramienta. Me apunto para la ayuda del video, aunque no he podido asistir a ninguna charla.

**Comment by jdjuan** [comment]
@Cdvalencia súper! Gracias! ¡Qué bueno que manejas AfterEffects, creo que va a ser muy necesario para nosotros! 👍 Déjame te actualizar a ti y @cardotrejos la próxima semana sobre cómo lo vamos a manejar! 😉

**Comment by Cdvalencia** [comment]
@jdjuan listo, quedo muy atento.
Me interesa mucho participar en el desarrollo del Video  :+1:

**Comment by davirom** [comment]
también hay otra alternativa que es **iMovie** se pueden crear videos fácilmente, si puedo ayudar en algo con el video quedo atento. 👍

**Comment by SantiagoMolinaOrozco** [comment]
✋ Presente again, nosotros tenemos una cámara semi profesional, lo que necesiten, nos cuentan 😋

**Comment by Cdvalencia** [comment]
@SantiagoMolinaOrozco, sería algo muy útil.
Se me ocurre ir tomando ejemplos de videos promo, en [vimeo ](https://vimeo.com/)hay bastantes muy buenos.

**Comment by jdjuan** [comment]
Creo que con NgColombia vamos a hacer un video promo pronto, así que por ahora voy a cerrar este issue 🙂
