### ISSUE TITLE
Arquitectura

### ISSUE THREAD

**Issue by angie-clau** [angular-medellin/meetup#48]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [X] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hola a todos, necesito recomendaciones de arquitectura para proyectos Angular, quiero hacer un buen uso de la programación por componentes, que me sugieren?, que documentación me recomiendan leer?... Gracias!.

**Comment by jdjuan** [comment]
Hola @angie-clau ! Te recomiendo tres cosas, a menos de que ya lo hayas hecho: 👌 

- [Hacer el Tour of Heroes de Angular](https://angular.io/tutorial)
- [Comprender la arquitectura de Angular para poder definir la tuya](https://angular.io/guide/architecture)
- [Y mirar las mejores prácticas!](https://angular.io/guide/styleguide)

Si lo hace y todavía tienes dudas, puedes escribirnos tus dudas más específicas 😸

**Comment by jdjuan** [comment]
@angie-clau no volvimos a oír de ti luego de la respuesta! 😀 Quedaste en shock!
