### ISSUE TITLE
Error: XMLHttpRequest cannot load field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by oscardmg** [angular-medellin/meetup#49]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [x] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
Problema la usar http.post

Tengo el siguiente error al usar el metodo post

XMLHttpRequest cannot load http://www.intranetlocal.com/api/api/test/users/register. Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

en el servicio tengo el siguiente codigo:

let url: string = 'http://www.intranetlocal.com/api/test/users/register';
    let headers      = new Headers({ 'Content-Type': 'application/json' }); // ... Set content type to JSON
    let options       = new RequestOptions({ headers: headers });

    return this.http.post(url , user, options) // ...using post request
      .map((res: Response) => res.json());

en el componente el siguiente:
this.userService.create(this.model)
      .subscribe(
        data => {
          console.log(data);
          this.router.navigate(['/login']);
        },
        error => {
          console.error(error);
          this.loading = false;
        });

Alguien le ha sucedido lo mismo?

muchas gracias a la persona que me pueda ayudar

**Comment by alejandronanez** [comment]
Óscar tienes CORS habilitado? Creo que ese puede ser el issue. Mejor dicho
tu backend debe aceptar peticiones de otros dominios, tal vez no lo està
haciendo.

**Comment by jdjuan** [comment]
@alejandronanez dio en el punto 🏹 También tuve el mismo error una vez y habilitar CORS fue la solución 👍

**Comment by oscardmg** [comment]
Si perfecto, adicione las siguientes lineas en el archivo httpd.conf y me funciono. muchas gracias.

Header always set Access-Control-Max-Age "1000"
Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"

**Comment by oscardmg** [comment]
En esta pagina encontre la solucion:

https://awesometoast.com/cors/

**Comment by alejandronanez** [comment]
Qué bien Óscar!

**Comment by oscardmg** [comment]
Muchas gracias por la ayuda!

**Comment by jdjuan** [comment]
Maravilloso! 👍 😁
