### ISSUE TITLE
Ionic - mobile apps

### ISSUE THREAD

**Issue by matew17** [angular-medellin/meetup#5]
- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

Me gustaría que pudiésemos recibir charlas acerca de ionic para que nuestras aplicaciones las podamos crear para mobiles, hay formas de trabajar ionic con angular y seria muy bacano poder aprender del tema, ya que la las aplicaciones móviles actualmente son la tendencia a nivel de software.

**Comment by jdjuan** [comment]
@matew17 gracias por proponer este tema! 💪 estoy seguro que a muchas personas les interesaría una charla de este tema. Creo que sería bueno que alguien hablara de **un primer acercamiento** en desarrollo híbrido con Angular, en lo que podría incluir:

- NativeScript
- Ionic
- Entre otros

¿Te gustaría preparar esta charla o alguien más estaría dispuesto?

**Comment by camigomez35** [comment]
Hola, Me gustaría participar siendo speaker de esta charla, aunque no tengo mucha experiencia (Ni como speaker ni en el tema :sweat_smile: ) quisiera aprender y empezar a participar activamente en la comunidad

**Comment by alejandronanez** [comment]
Súper @camigomez35 🤘🏼

**Comment by jdjuan** [comment]
@camigomez35 Wow!, eso es genial! 🥇 

Tus aportes son bienvenidos, nos alegra mucho que quieras participar 👏 y no te preocupes, tu charla no tiene que ser muy compleja 😉 

Recuerda que:

> En Angular Medellín le ponemos mucha atención al contenido que le mostramos a nuestros miembros, darle el enfoque adecuado a la charla será clave para salgas en hombros del auditorio 🌟

Empieza a construir tu presentación y mándame un email (david.juanherrera@gmail.com) cuando la tengas lista 👍 

![1pvrp1](https://cloud.githubusercontent.com/assets/3171900/26533185/83fadb44-43da-11e7-8184-610e8b444acf.jpg)

**Comment by apipemc** [comment]
Si necesitan temas de apoyo.
Tengo bastante conocimiento y he realizado varias aplicaciones con estos frameworks:
- NativeScript
- Ionic 1 y2

**Comment by jdjuan** [comment]
Maravilloso @apipemc ! Gracias por tu apoyo 🏅 

Ahí lo tienes @camigomez35 ! Pueden charlar en el próximo meetup 👍

**Comment by camigomez35** [comment]
Muchas gracias a todos por el apoyo :3 estaré estudiando para entregar lo mejor de mi y @apipemc estamos hablando 😺

**Comment by jdjuan** [comment]
@camigomez35 acabo de subir unas recomendaciones para los speakers de Angular Medellín, échale un ojo! 👀  

**[SPEAKERS GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md)**

**Comment by camigomez35** [comment]
@jdjuan acabo de revisar la guía para los speaker y veo que debería hacer un issue hablando de mi  😄 aún lo debo hacer 😝 yo no soy muy buena con eso 😅

**Comment by jdjuan** [comment]
@camigomez35 no te preocupes! 😄 puede ser algo breve. Y no tienen que crear otro issue, puedes hacerlo aquí mismo para mantener una traza 😁

**Comment by camigomez35** [comment]
📱 Hola, mi nombre es Maria Camila Gómez Restrepo 💃 

Soy estudiante de noveno semestre de ingeniería de sistemas de la Universidad de Antioquia 🤓 , trabajo como Auxiliar de programación en el Departamento de recursos de apoyo e informática de la U, principalmente en iOS, y próximamente empezaré a trabajar en la empresa [Experimentality](https://www.experimentality.co/) como desarrolladora. 
Pertenezco a la comunidad de Pioneras Developers y me encanta asistir a los distintos meetups que hay en la ciudad.

Con respecto a la charla me gustaría desarrollarla de la siguiente manera:
1. Introducción a ionic (¿Qué es, qué necesitamos y como instalarlo?)
2. Uso de la documentación de [ionic framework](https://ionicframework.com/)
3. Creación de proyectos de ionic (comandos)
4. Estructura de un proyecto
5. Correr localmente nuestras apps (comandos)
6. ¿Cómo podemos utilizar la app 'ionic view'? (descargarla)
7. Subir nuestra app al dashboard de ionic (comandos)
8. Problemas que se pueden presentar al usar el ionic view app

El tiempo estimado es de 1 hora o un poco menos.

Estoy muy emocionada y espero sea de su agrado. 👩 💻

**Comment by jdjuan** [comment]
Súper @camigomez35 ! Se nota que estructuraste muy bien la charla! 🥇 👍 
Creo que ya tenemos luz verde para comenzar, asegúrate de enviarme las diapositivas para darte un feedback final y entonces hacemos público el anuncio de tu charla!  👩‍🚀

**Comment by alejandronanez** [comment]
@camigomez35 genial! Qué bueno que te animes a dar la charla, eso anima a más personas a seguir compartiendo!

**Comment by cortizqgithub** [comment]
Este tema fue presentado como charla en el Meetup Nro 4 de Jul.12/2017. Ya se puede dar por cerrado este tema. Por supuesto no soy yo quien puedo hacer esto.

**Comment by jdjuan** [comment]
Gracias @cortizqgithub ! Tienes toda la razón! 👍
