### ISSUE TITLE
Debugging Angular apps created with Angular CLI in WebStorm

### ISSUE THREAD

**Issue by oscardmg** [angular-medellin/meetup#50]
- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Saludos!

A las personas que usen WebStorm les recomiendo este articulo: https://blog.jetbrains.com/webstorm/2017/01/debugging-angular-apps/

Ya lo probé y funciona muy bien, espero les sirva!

Si alguien quiere usar WebStorm y no tiene licencia pero actualmente esta estudiando o tiene un correo de alguna universidad o institución educativa, se pueden registrar como estudiante y te dan una licencia por una año para usar todas las herramientas de JetBrains

**Comment by jdjuan** [comment]
¡Qué buena recomendación @oscardmg! Muchas gracias, WebStorm es uno de los mejores IDEs, me alegra que lo estés usando, dejaré este issue abierto un tiempo para que a las personas les pueda servir de referencia! 👌 🥇
