### ISSUE TITLE
Crear perfiles en redes sociales de la comunidad

### ISSUE THREAD

**Issue by MelinaMejia95** [angular-medellin/meetup#51]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hola a todos! 😄 
Sería genial que nuestra comunidad tuviera perfiles en otros sitios oficiales, no sólo en GitHub, para que mucha más gente pueda conocerla! 
Facebook, Twitter, Instagram, incluso LinkedIn, serían buenas opciones, donde compartamos información de la comunidad, de nuestros speakers, meetups, proyectos...
¿Qué les parece? 😁

**Comment by jdjuan** [comment]
Súper @MelinaMejia95 ! Creo que Twitter es el lugar más indicado para empezar con las redes sociales! De cualquier modo, es bueno publicar contenidos al menos 1 vez por semana! Sería algo así como un Community Manager ¿Quién nos da una mano? 😀 😀

**Comment by H4isan** [comment]
😃 No entiendo mucho pero yo puedo ser ese Community Manager. if no hay problem

**Comment by jdjuan** [comment]
¡Esoooo! 🌵 Necesitamos al menos alguien más! Quién nos da una ✋

**Comment by pablovem** [comment]
Redes Sociales:
* [Twitter](https://twitter.com/angularmedellin/)
* [Instagram](https://www.instagram.com/AngularMedellin/)
* [Facebook](https://www.facebook.com/Angular-Medellin-1894781607456246/)

**Comment by danielcb29** [comment]
@pablovem que tal LinkedIn 😄  ?

**Comment by pablovem** [comment]
Hola @danielcb29, LinkedIn podria ser una buena opción, tanto por el tráfico de personas relacionadas con tecnología (devs, reclutatores, etc) como por la posibilidad de colaboradores que tengan `AngularMedellin` en sus CVs.

@jdjuan consideras pertinente crearla entonces?

**Comment by jdjuan** [comment]
@pablovem @danielcb29 Me parece una buena opción, así las personas podrían tener en sus perfiles la participación que han tenido de la comunidad! ⭐️ 

Propongo que terminemos de crear y fortalecer el Facebook, el Twitter y el Medium, y entonces pasamos a LinkedIn

FYI @H4isan 

¿Les parece?

**Comment by pablovem** [comment]
Perfecto, sigamos ese plan 👍 .

**Comment by jdjuan** [comment]
Terminado 👍
