### ISSUE TITLE
renderizado de componentes por rutas 

### ISSUE THREAD

**Issue by mauro1998** [angular-medellin/meetup#52]
# Me gustaría...
- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [x] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Supongamos que tengo un gran componente padre constituido por varios componentes a su vez cuyo renderizado depende de parametros por ruta.

Varios de estos componentes padres se encuentran listados en la pagina principal (un preview de ellos). Al darle click a uno de ellos la aplicacion navega hacia ese componente en especifico, lo muestra en el router-outlet y comienza a cargar sus componentes hijos. Todo bien hasta el momento.

Digamos que la ruta luce algo asi: `/components/:id`.

La pagina del componente muestra un largo scroll debido al gran volumen de contenido (dinamico) que tiene el componente.

**El problema:** 

El componente padre, al final del scroll hace referencia a un componente hijo que se encarga de listar otros componentes padres relacionados al componente actual y tienen el mismo funcionamiento que en la pagina principal. 

Cuando se navega hacia alguno de estos componentes la ruta vuelve a cambiar pero Angular no vuelve a cargar el componente porque ya lo ha instanciado la primera vez que se visitó desde el principio de la aplicación, por lo tanto lo que hace es simplemente reemplazar el contenido dinámico y lo demás queda tal cuál, incluso la posición actual del scrollbar, haciendo que sea casi imperceptible el cambio.

Recomendaciones?
Gracias de antemano.

**Comment by jdjuan** [comment]
Hola @mauro1998 ! 😄 

Al parecer el problema es éste? 

> y lo demás queda tal cuál, incluso la posición actual del scrollbar, haciendo que sea casi imperceptible el cambio.

Qué tal si vuelves y subes el scrollbar automáticamente? 🤔 

PS: Si pones unos screenshots podría ser más ayuda para entender 😁

**Comment by jdjuan** [comment]
@mauro1998 no olvidemos a oír de ti luego de la respuesta? 😁 Quedaste en shock!
