### ISSUE TITLE
Compilar proyecto en un solo script (js)

### ISSUE THREAD

**Issue by angiefrancop** [angular-medellin/meetup#53]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [X ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
Hola, 
Podrían decirme como puedo hacer para que al compilar mi proyecto a producción los scripts me queden en un solo .js?. Muchas gracias por su ayuda.

**Comment by alejandronanez** [comment]
hola angela, estas utilizando angular-cli? O tienes una configuracion de
proyecto 'custom'?
Si tienes angular-cli puedes correr npm run build si no estoy mal.

**Comment by angiefrancop** [comment]
Si tengo angular cli, con ese comando me genera en la carpeta "dist" los archivos: 

- inline.bundle.js 
- main.bundle.js 
- polyfills.bundle.js
- styles.bundle.js
- vendor.bundle.js 

Lo que quiero es que todos esos archivos queden en un solo .js

**Comment by jdjuan** [comment]
@angiefrancop es una muy buena pregunta, la verdad nunca lo he hecho, tienes algún motivo para hacerlo en especial? ¿Hay alguna alternativa?

Recuerda que Webpack genera varios archivos precisamente para mejorar el performance de la aplicación, sin juntas todos los archivos en uno, vas a hacer que tu aplicación cargue un poco más lento 🤔

**Comment by angiefrancop** [comment]
Hola 😄  @jdjuan la verdad me pidieron entregarlo así, van hacer una especie de librería nativa tanto para android como para ios que levante la aplicación Angular en un webview 😓.

**Comment by alejandronanez** [comment]
Creo que puedes revisar un paquete de npm que haga el concat de los
archivos. Hay uno que se llama concat-files. Puedes hacer el build y luego
corres el comando para que los concatene todos.

**Comment by jdjuan** [comment]
@angiefrancop algún update? Pudiste resolverlo? Cómo te fue con la librería que propuso @alejandronanez ? 🤔

**Comment by angiefrancop** [comment]
Chicos gracias por su apoyo, intentaré con el paquete de npm 😉

**Comment by jdjuan** [comment]
Está bien @angiefrancop ! 😁
