### ISSUE TITLE
Canal de youtube para streaming en el futuro

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [angular-medellin/meetup#54]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Muchos meetups tienen canal en youtube donde hacen streaming, una charlita en el mes, corta por streaming no estaría mal, es una sugerencia :yum: 

Excelente meetup :yum:  sigan así.

**Comment by SantiagoMolinaOrozco** [comment]
Después de hacer el issue, me di cuenta que en otro issue alguien comento algo parecido, aun así dejo este issue para que la idea no se pierda, ya si los administradores lo desean pueden borrarlo.

**Comment by jdjuan** [comment]
¡Buenísima idea! 💡  💡  💡  
Creo que puede ser muy divertido, cada persona puede ver el streaming desde su casa, y podemos tener más invitados, incluso un panel de discusión, entre otros temas! 🎉 

Empezaré a buscar a los panelistas! 👍

**Comment by SantiagoMolinaOrozco** [comment]
Yo muchas veces no puedo ir a los meetups en semana, cuando son en youtube, muchas veces puedo ver las repeticiones en la noche o cuando tengo tiempo disponible.

seria muy genial :yum: gracias @jdjuan  excelente meetup :yum:

**Comment by jdjuan** [comment]
Gracias a ti @SantiagoMolinaOrozco ! Eres un miembro muy activo! 😁 

Comunidad!, necesitamos una mano con esta idea, alguien quiere ayudarnos a hacerla realidad? ✋

**Comment by jdjuan** [comment]
Ya tenemos canal! Pueden verlo aquí! https://www.youtube.com/channel/UCHA3Bs7x8f89X9TtFnmsqLQ

Pronto subiremos el último meetup! 😁

**Comment by SantiagoMolinaOrozco** [comment]
Muchas gracias, Estaré pendiente 😋 ya que no pude asistir  al ultimo meetup 😋
