### ISSUE TITLE
Generación de imágenes adicionales build (--aot)

### ISSUE THREAD

**Issue by camilo56** [angular-medellin/meetup#55]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [x] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hola a todos

Actualmente estoy trabajando en un proyecto que esta pronto a finalizar y me tope con un ligero inconveniente, al generar el build (ng build --prod) me genera los archivos finales comprimidos pero adicional mete también me esta generando algunas de las imágenes que tenia en la carpeta assets fuera de la misma (carpeta dist), y los  estilos que apuntan a dicha imagen quedan diseccionados a la imagen generada fuera de la carpeta assets y no a la que esta en su interior.

Alguna idea de porque puede suceder esto? 

Gracias

**Comment by jdjuan** [comment]
@camilo56 buena inquietud! 🤔 bueno creo que pueden haber diferentes razones. Es posible que tu Angular CLI está configurado para hacerlo así ... pero en general, cuando tienes imágenes dentro de la carpeta assets quedan allí dentro.

¿Qué tal si nos muestras más información y tal vez un repo donde podamos ver ese comportamiento? 😁

**Comment by camilo56** [comment]
Hola, es un proyecto que estoy realizando en mi trabajo y no podría compartir el código, pero lo genere con angular cli y no modifique su configuración.
Las imágenes si se quedan en la carpeta assets, el problema es que el build genera una copia de algunas imagen (tres para ser exactos) y las pone fuera de dicha carpeta, adicional mente los estilos apuntan a las imagenes de afuera de la carpeta assets por los cual no puedo eliminarla tendría que modificar manualmente el código generado para que apuntara a la ruta correcta. 

Alguna idea?.
Gracias.

**Comment by jdjuan** [comment]
@camilo56 🤔 es verdaderamente difícil saber dónde podría estar la causa, la verdad no me ha pasado algo parecido. ¿Qué tal si creas un repo nuevo e intentas reproducir el error? Así podríamos compartírnoslo y darte una solución? 👍
