### ISSUE TITLE
Problemas de rendimiento :(

### ISSUE THREAD

**Issue by henryzarza** [angular-medellin/meetup#56]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [x] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
Hola, buenos días. 

Me encuentro desarrollando un proyecto pero este tiene problemas enormes en cuanto al performance al punto que cuando escribo en un input se demora aproximadamente 10 segundos en asignarle el valor, he leído y al parecer es por los Change Detection, una solución fue colocar todos los componentes con ChangeDetectionStrategy.OnPush, para que no se disparara tanto el change detector del componente, pero el performance no ha mejorado.

Hice un console.log en el AfterViewChecked de uno de los componentes y entra a este demasiadas veces, incluso cuando hago acciones que no tienen nada que ver con el componente (lo cual me da a entender que el change detector de ese componente se esta disparando). Lo mas extraño es que hice un console.log en otro y en ese no se activa casi.

### ¿Qué puedo hacer para solucionar este problema?

Muchas gracias al que me pueda ayudar.

**Comment by jdjuan** [comment]
Hola @henryzarza ! 🤔 interesante problema!

El rendimiento de una aplicación es clave, y es una lástima que estés teniendo estos problemas.

¡Qué bueno que ya le echaste un ojo al ChangeDetection! Es un buen lugar para comenzar. Algo más que puedes analizar es **ngZones**!

En [este artículo](http://blog.mgechev.com/2017/01/17/angular-in-production/) Minko tuvo algunos problemas de rendimiento al momento de hacer una aplicación y explica cómo resolvió cada uno. Échale un ojo, es bien fácil de 

Tal vez podamos ayudarte más fácil si puedes replicar tu problema en un repositorio, así podemos clonarlo y ayudarte a resolverlo.

Déjanos saber! 😁

**Comment by henryzarza** [comment]
Hola @jdjuan muchas gracias, investigando y junto con unos compañeros logramos identificar que el problema era que estábamos enviando una cantidad considerable de datos por unos inputs, es que tenemos un wrapper del select 2 y la data se la estabamos enviando por ahí y como tenemos 19 ya te imaginarás la carga. 
Me sirvió mucho lo de ngZones y lo del Change Detection.

Muchas gracias y buena vibra!!

**Comment by jdjuan** [comment]
@henryzarza me alegra que lo pudieras solucionar! 😁 

Ahora que lo pienso no estaría mal hacer una sesión en Angular de errores comunes. Algo así como Fuck Up Nights, pero de cosas con angular 👺 

Vos te animarías a contarnos (sin mencionar nada confidencial) en 15 minutos cuál fue el error que cometiste y cómo lo solucionaste?

**Comment by henryzarza** [comment]
Hola @jdjuan no tengo mucha experiencia manejando Angular, lo comencé a manejar hace poco, pero aún así me gustaría hablar un poco de las cosas que me han pasado y de experiencias de compañeros y conocidos.

Excelente inicio de semana :smile:

**Comment by jdjuan** [comment]
Listo. Creado en #59
