### ISSUE TITLE
Hagamos nuestro Website en Angular 😄

### ISSUE THREAD

**Issue by Fabian-Buitrago** [angular-medellin/meetup#57]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hola muchachos,

Anteriormente notamos que se ha propuesto un issue para crear un foro por y para la comunidad, pero que tal si adicionalmente hacemos nuestra pagina oficial?

**Comment by jdjuan** [comment]
¡Me gusta la idea! ¿Quién se anima a participar de este proyecto? 😀

**Comment by danielcb29** [comment]
@Fabian-Buitrago @jdjuan Excelente idea!, desde form-project teníamos la intención de darle cara a la landing page, sin embargo, no se tenían separadas ambas ideas. Podríamos unir esfuerzos y seguir con la idea de implementar el form en la misma landing page (como método de inscripción - confirmación de asistencia). 

@Fabian-Buitrago Podríamos incluirte en el proyecto y mostrarte el avance que se tiene 😄. Como equipo podemos decidir si es mejor separarlo o trabajarlo junto a form

**Comment by Fabian-Buitrago** [comment]
@danielcb29 de una, entonces apenas me incluyan en el proyecto me comunicare con vos para mas info

**Comment by prisskreative** [comment]
@Fabian-Buitrago @jdjuan @danielcb29  Super la idea!! Me gustaria colaborar en este proyecto ✋😀

**Comment by juancapm09** [comment]
Me gustaria participar en este proyecto. @jdjuan @Fabian-Buitrago @danielcb29 @prisskreative

**Comment by jdjuan** [comment]
@juancapm09 @prisskreative @Fabian-Buitrago @danielcb29 Me parece fabuloso! ¡Qué bueno tantas personas animadas! 🎉 🎉 

Búsquenme en el próximo meetup y les cuento cómo vamos a hacerlo! 🔥

**Comment by cardotrejos** [comment]
Me gustaría participar también. :fire: :hand:

**Comment by henryzarza** [comment]
A mi también me gustaría participar :hand:

**Comment by josueggh** [comment]
✋

**Comment by fmauricios** [comment]
:hand:

**Comment by Estoja** [comment]
Me gustaría participar :hand:

**Comment by jdjuan** [comment]
Vea usted! 😁 ¡Qué muchachos tan motivados!
Asegúrense de buscarme en el próximo Meetup y les cuento cómo va a ser. 😀

**Comment by oscardmg** [comment]
No pude asistir al pasado meetup, pero estoy interesado en participar!!

**Comment by davirom** [comment]
✋

**Comment by EsneiderSM** [comment]
✋

**Comment by SantiagoMolinaOrozco** [comment]
✋ Saben que lo que necesiten, pueden contar con migo 👍

**Comment by jdjuan** [comment]
Aquí está! 🅰️ 
http://angularmedellin.com/
