### ISSUE TITLE
Una pantalla adicional para los meetups

### ISSUE THREAD

**Issue by Fabian-Buitrago** [angular-medellin/meetup#58]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Hola Muchachos,

Hemos crecido mucho como comunidad y en cada charla llegan mas y mas personas pero a mitad de auditorio no se es fácil ver información de las diapositivas, seria bueno que colocáramos una pantalla mas, entonces que tal si entre todos buscamos una solución a este problema?

**Comment by jdjuan** [comment]
¡De acuerdo! A pesar de que hacemos todo lo posible para que los contenidos se puedan ver desde la parte de atrás del auditorio creo que no es suficiente 😪 

Y es cierto, cada vez somos más en el meetup 🤔, pronto no tendremos ni siquiera espacio ¿Tal vez sea el momento de buscar otro auditorio?

- Uno que tenga espacio de sobra
- Que tenga buena buena visibilidad para los asistentes
- Y con un internet más rápido

¿No les parece? 😁

**Comment by danielcb29** [comment]
@jdjuan otro auditorio ubicado en la zona ciudad del rió complementaría yo jajajaja :stuck_out_tongue_winking_eye: . Ruta N podría ser otra opción, sin embargo no conozco que auditorios grandes hay allí.

**Comment by Fabian-Buitrago** [comment]
@danielcb29 ya que contamos con una comunidad bastante grande, seria bueno preguntarles que sitios conocen que se acomoden a nuestras necesidades.

**Comment by JamesChe91** [comment]
Ruta N me parece bueno, y en las salas q' he estado está la pantalla grande y adicional dos televisores, uno en cada lateral del salón.

**Comment by MelinaMejia95** [comment]
@JamesChe91 Siii! Los auditorios de RutaN serían perfectos! Tanto por el espacio, como por todass las pantallas que hay!

**Comment by jdjuan** [comment]
De acuerdo! Ya estamos gestionando. El de la Universidad de Antioquia fue muy bueno! Vamos a analizar cómo procedemos! 👍

**Comment by jdjuan** [comment]
De ahora en adelante buscaremos auditorios modo teatro para garantizar la visibilidad modo teatro 👍
