### ISSUE TITLE
Fuckup nights - Angular Medellín

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#59]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Siguiendo la idea de [fuckupnights.com](https://fuckupnights.com/), ¿Qué tal si hiciéramos un meetup en el que diferentes speakers compartieran las malas decisiones que tomaron al trabajar con Angular? Un lugar donde nos contaran su experiencia sobre cosas que hicieron mal y cómo podemos evitarlas 😀 

Por ejemplo: #56 

@henryzarza y yo vamos a hacerlo. ¿Quién más se anima? 👕 

No tiene que ser ninguna gran anécdota, sólo basta con que nos cuentes un problema que tuviste y cómo lo solucionaste! 👍

**Comment by jdjuan** [comment]
Esta idea es muy buena, por qué nadie la apoya 😢

**Comment by henryzarza** [comment]
A mí me parece genial la idea, el hecho de compartir experiencias y malas vivencias nos hace crecer como desarrolladores. Yo me apunto totalmente

**Comment by jdjuan** [comment]
Tal vez luego podamos iterar esta idea más, por ahora la voy a cerrar 🙂
