### ISSUE TITLE
Oportunidad para practicar Inglés!! 

### ISSUE THREAD

**Issue by MelinaMejia95** [angular-medellin/meetup#6]
# Hola a todos!!! :smiley:
Estuve hablando con Juan sobre cómo podríamos poner en práctica nuestro inglés. 
En Envigado hay una escuela de idiomas, Colombia Immersion, todos los viernes se hace una reunión alrededor de las 6:30 - 7:00 pm. Cualquiera puede ir (IT'S FREE!! :tada:), en cada reunión se hace una actividad de integración, como bingos, conversatorios, juegos de mesa... (Venden cerveza y a veces dan pasabocas :beers: !!!!)
Van personas de todas partes del mundo 🌎 ! Es una gran oportunidad para practicar inglés y quitar ese "miedo" de hablarlo con nativos del idioma.

Anímense!! :confetti_ball: 
Esta es la dirección: Carrera 40 #40D Sur - 49 

Para más información de la escuela: https://www.facebook.com/colombiaimmersion/
http://www.colombiaimmersion.com/

**Comment by jdjuan** [comment]
@MelinaMejia95 muchas gracias por tu aporte! 😊 👍 Estoy seguro que a muchas personas les gustaría ir a este meetup. Y ahora que lo mencionas, me gustaría que tu contribución trascendiera a lo largo del tiempo. Creo que sería bueno que agregáramos un espacio (en este repositorio) para referenciar recursos en inglés que sirvan a nuestra comunidad. Tú idea sería la primera, pero podemos agregar muchos más.

¿Qué opinas? Si te interesa la idea, por qué no creas un PR agregando un archivo a la raíz del directorio llamado: **PRACTICE-ENGLISH.md**

**Comment by MelinaMejia95** [comment]
@jdjuan Listo! :D

**Comment by jdjuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3171900/25828971/05d7efca-3419-11e7-98da-c5c87541e897.png)
