### ISSUE TITLE
Crear enlace a tutoriales, complementos, etc.

### ISSUE THREAD

**Issue by cortizqgithub** [angular-medellin/meetup#60]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ x] 🤡 Otro

## Descripción

Ya en el issue #19 se ha propuesto esto, pero no encuentro donde lo han resuelto y como puedo apoyar en conectar estos enlaces.

**Comment by jdjuan** [comment]
Hola @cortizqgithub ! 

Échale un ojo al archivo **[RESOURCES.MD](https://github.com/angular-medellin/meetup/blob/master/RESOURCES.md)**, si quieres agregar algo sólo basta con que hagas un PR! 🐤
