### ISSUE TITLE
D3 with Angular 😎 📊 

### ISSUE THREAD

**Issue by danielcb29** [angular-medellin/meetup#61]
# Me gustaría...

- [X] 😎 Ser el próximo speaker
- [X] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

**💬  Angular + D3**

Hey Angular Med Team!

A few days ago I was thinking about "What about charting in Angular?", so , I thought , what about D3 and Angular?. 
I'm currently working with D3 , Crossfilter, DC , ES6 and other technologies building an awesome chart lib for Autodesk. I'm really excited to talk about what I'm doing and how can you start in this awesome Charting world 🎉, also, using it in Angular 😉 . 

What do you think? Do you you wanna know about D3 + Angular? 

**☝️  About Me** 
- Software Engineer focused on UI development, SOA and DevOps culture. 💻 
- Angular Medellín active member 🍰 
- Web UI Software Engineer at Globant (Autodesk) 👨‍💻 
- Univalle 👨‍🎓 

**⏰  Time**

30 Minutes

Thanks for the opportunity Angular Medellín!

**Comment by jdjuan** [comment]
Wooohooo!, you are all set! We are super excited to see this! 🎉 Send me your slides as soon as you have them! 😁 Great intro!

**Comment by jdjuan** [comment]
☎️ Aló, por favor @danielcb29  , ¿No se encuentra? 😲, ah bueno, para dejarle una razón. Que si porfa envía las diapositivas 😁

**Comment by danielcb29** [comment]
@jdjuan Heyyy!, aquí estoy, algo perdido pero vivo jajaja, enviada la primera versión (beta 😅 ), espero feedback mientras termino los últimos detalles 😎

**Comment by jdjuan** [comment]
Well done buddy!
