### ISSUE TITLE
Unconscious Bias - Haciendo lo inconsciente consiente

### ISSUE THREAD

**Issue by marianvilla** [angular-medellin/meetup#62]
#

# Me gustaría...

- [x] 😎 Ser el próximo speaker
- [x] 😃 Proponer un tema 

## Descripción

**Unconscious Bias - Haciendo lo inconsciente consiente** 
Todos tenemos estereotipos, y culturalmente un montón de sesgos cognitivos que nos permiten ver el mundo según nuestro modelo único. Estos son los “shortcuts” que nuestro cerebro utiliza para poder procesar la información que recibimos cada día. Cuando vemos a alguien inmediatamente nuestro cerebro genera juicios, porque nuestro cerebro es experto en llenar los espacios en blanco, y así necesitamos generar tags clasificando que tan amigable o agradable es; qué tan parecido o no es a mi, y según esta respuesta decido, qué tan capaces son de hacer X o Y tarea. 

**About Me**
👩‍💻 Graphic Designer & Front End Developer, 💪Core-team member of @Pionerasdev 👩‍🏫 Teacher of Interactive Media Communications 👩‍💼 CEO of eversocial.co 👩‍🎓 MBA Marketing 📉 #BigData #SmartData

**Time** 
⏰ 40 minutos

**Comment by jdjuan** [comment]
Súper @marianvilla ! Muy contentos de tenerte en nuestro meetup! Muy buena introducción! 👍 😀 

No olvides echarle un ojo a nuestros **[Speaker Guidelines](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md#-speakers-)** para que la saques del estadio! 🎉 

Envíame tus diapositivas cuando estén listas para darte feedback! ⚡️

**Comment by jdjuan** [comment]
Muy bien Marian! 🥇
