### ISSUE TITLE
Nativescript with Angular 

### ISSUE THREAD

**Issue by cortizqgithub** [angular-medellin/meetup#63]
# Me gustaría...

- [x] 😎 Ser el próximo speaker
- [x] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
Al crear aplicaciones hibridas para plataformas mobiles existen dos consideraciones, las totalmente nativas y las hibridas, y dentro de éstas estan las que usan un WebView y un acercamiento más hacia lo nativo sin ser programado como tal, Nativescript es uno de estos frameworks que se acercan más a realizar una aplicación mobil cercano a lo nativo.

Se usa herramientas como HTML/CSS/Javascript que son ubicuas hoy en día en el mundo WEB, pero con éste se intenta acercar estas tecnologias para crear aplicaciones mobiles.

Me postulo como SPEAKER como reto y compartir con la comunidad (con la ayuda de los organizadores para lograr el objetivo).

**Comment by jdjuan** [comment]
Hooray! ¡Qué buen tema! Muchas personas lo estaban esperando! Recuerda leer los **[SPEAKER GUIDELINES](https://github.com/angular-medellin/meetup/blob/master/SPEAKERS.md#-speakers-)**.

Envíame tu presentación tan pronto la tengas! 😀

**Comment by cortizqgithub** [comment]
Muy bien, ahora que ya está el issue abierto, hay que trabajar en él. Para tal fin jdjuan me gustaría poner el logo de Angular-Medellin (el que tiene las calcomanias que nos diste en la pasada reunión), para que haga parte de los slides, igualmente.

Cuando tenga los slides te los hago saber para su revisión.

Una cosa más, de cuanto tiempo se tiene disponible para la charla.

**Comment by jdjuan** [comment]
@cortizqgithub lo puedes tomar de [aquí](https://s3.amazonaws.com/media-p.slid.es/uploads/16425/images/4035760/angular_logo-02.png) 😉 

Tienes entre 15 y 40 minutos 😁

**Comment by cortizqgithub** [comment]
Ya tengo la imágen, gracias.

**Comment by cortizqgithub** [comment]
Ya envié la presentación para su revisión.

**Comment by jdjuan** [comment]
Muy bien @cortizqgithub ! 🥇
