### ISSUE TITLE
Angular Medellín: Hecho para vos - Correcion

### ISSUE THREAD

**Issue by adrendon** [angular-medellin/meetup#66]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [x] 🤡 Otro

Hola podrian corregir los slides de **GraphQL y Angular**

Muchas gracias

**Comment by jdjuan** [comment]
Hola @adrendon ! Mil gracias por la corrección! 🥇 🙂 Ya está! 

https://github.com/angular-medellin/meetup/tree/master/meetups/4-angular-medellin-hecho-para-vos
