### ISSUE TITLE
Unificar los slides con una plantilla común

### ISSUE THREAD

**Issue by cortizqgithub** [angular-medellin/meetup#67]
# Me gustaría...

- [x ] 🤡 Otro

## Descripción
Ahora que el meetup tiene logo, que tal si también los slides usan este logo y que además tengan uno o más plantillas para así darle identidad al grupo.

**Comment by jdjuan** [comment]
Hola @cortizqgithub !

Me agrada tu idea! Creo que sería bueno que los speakers pongan el logo de Angular Medellín, sin embargo no lo podría en todas las diapositivas, al menos en la primera 😁 

En nuestra comunidad cada speaker puede diseñar sus propias diapositivas si así lo desea, pero si quieres una plantilla yo te la puedo prestar 😉

**Comment by cortizqgithub** [comment]
De hecho por el contrario yo creo que si es bueno tener el logo de Angular Medellin en todas las diapositivas porque de esta forma le da fuerza a la presentación y se evidencia que es de Angular Medellín.

**Comment by jdjuan** [comment]
Vale! @cortizqgithub regálame tu cuenta de slides.com para compartirte la plantilla! 👍
