### ISSUE TITLE
Uso de Microfono inalambrico o manos libres

### ISSUE THREAD

**Issue by cortizqgithub** [angular-medellin/meetup#68]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [x] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
En los meetup anteriores siempre que se hace un demo el presentador tiene que estar manipulando el computador y a su vez tener el microfono en la mano para poder continuar con la exposición lo cual veo que es engorroso para la continuidad en la presentación. Sería deseable considerar la posibilidad del uso de microfono inalambrico o algún otro mecanismo que permita liberar las manos al presentador cuando este haciendo los demos y así manipular el código o comandos para tal fin.

**Comment by jdjuan** [comment]
Gran aporte @cortizqgithub ! 👍 
Tienes toda la razón, sería mejor pues así los speakers podrían codificar sin preocuparte por sostener el micrófono al mismo tiempo! 🎤 

Voy a empezar a gestionar a ver si en el auditorio nos lo pueden prestar! 🙂

**Comment by cortizqgithub** [comment]
Excelente. Aunque no sobraría saber si el patrocinador pueda aportar este elemento para que sea propio.

**Comment by jdjuan** [comment]
Tal como en #58 empezaremos a utilizar auditorios modo teatro y con todas las condiciones de sonido para que podamos hacerlo así! 👍
