### ISSUE TITLE
Formularios en Angular

### ISSUE THREAD

**Issue by CrisDan1905** [angular-medellin/meetup#69]
# Me gustaría...

- [x] 😎 Ser el próximo speaker
- [x] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Una de las herramientas mas poderosas y practicas que tiene angular son los formularios, mediante estos podemos ingresar nuestro usuario y contraseña para ingresar a un sitio, reservar unos pasajes o simplemente llenar una solicitud. sin embargo he notado que nadie ha hablado hasta ahora de ellos. Me gustaría realizar una introducción a los formularios, ¿Que son los formularios de angular? ¿que tipos hay? ¿Como se validan?. 

Que opinan? :smile: 

:point_up:  Tecnologo en electrónica seducido por el lado oscuro (la programación), Front-end web developer  apasionado por lo que hace, trabajando con Angular desde hace casi 1 año

:alarm_clock: Aproximadamente 30 mins

**Comment by jdjuan** [comment]
Genial @CrisDan1905  ! 😁 Le diste al 🎯 con este tema!   

Me parece genial, muy bien, estaré ansioso de ver esta charla! 🅰️

No olvides echarle un ojo a nuestros **[Speaker Guidelines](https://github.com/angular-medellin/meetup/blob/master/assets/SPEAKERS.md#-speakers-)** para que la saques del estadio 🎉 

Envíame tus diapositivas cuando estén listas para darte feedback! ⚡️

**Comment by jdjuan** [comment]
☎️ Aló, por favor @CrisDan1905 , ¿No se encuentra? 😲, ah bueno, para dejarle una razón. Que como van esas diapositivas!

**Comment by CrisDan1905** [comment]
😱 mil disculpas. Se me han presentado algunos inconvenientes y por eso aún no las he podido terminar. En esta semana que viene te las paso✋

**Comment by CrisDan1905** [comment]
**De esta semana que viene 😧

**Comment by jdjuan** [comment]
@CrisDan1905 Te recuerdo que vas de primero en nuestro primer meetup del 2018! Te mantendré al tanto! 👍

**Comment by CrisDan1905** [comment]
@jdjuan muchas gracias, estaré pendiente 😀😀
