### ISSUE TITLE
Reconozcamos a nuestros contribuyentes en nuestro readme.md

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/meetup#7]
# Me gustaría ...  

`(Selecciona con una "x" => [x])`

- [ ] **Ser el próximo speaker** => Escribe los detalles de tu charla
- [x] **Proponer un tema o mejora** => Qué te gustaría y por qué
- [ ] **Dar mi retroalimentación** => ¡Gracias!, esto nos hace crecer
- [ ] **Convertirme en organizador** => Explícanos por qué y cómo puedes aportar
- [ ] **Otro**

## Descripción

Nuestro `readme.md` está lleno de emoticones y es agradable a la vista 👀, pero hace falta lo más importante: Mencionar a nuestros contribuyentes 👨👩 Agreguemos una sección a nuestro `readme.md` siguiendo el estándar de [all-contributors](https://github.com/kentcdodds/all-contributors#contributors) para resaltar a los miembros más activos de esta comunidad

(❤️️ si quieres que aprovemos esta mejora)

**Comment by alejandronanez** [comment]
Yo agarro este issue. Esperen el PR. 👍

**Comment by jdjuan** [comment]
![05d7efca-3419-11e7-98da-c5c87541e897](https://cloud.githubusercontent.com/assets/3171900/25860239/9528ad1c-34a6-11e7-8fa2-923239371be4.png)
@alejandronanez
