### ISSUE TITLE
Optimizar la imagen del Readme 

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [angular-medellin/meetup#70]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [x] 🤡 Otro

## Descripción

La imagen del Readme pesa 5.5MB eso en la web es mucho, ademas de que es un jpg, 😋  cuando el internet se pone flojo carga como en los años 90 😄  

Es solo una pequeña recomendación para mejorar. 

Todas las imágenes en  la web tienen que estar optimizadas para mejorar la experiencia de los usuarios 👍

**Comment by jdjuan** [comment]
hahahahah @SantiagoMolinaOrozco tienes toda la razón! 😅 Ya mismo la organizo
