### ISSUE TITLE
Rxjs - operadores

### ISSUE THREAD

**Issue by camilo56** [angular-medellin/meetup#71]
# Me gustaría...

- [x] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción

Me parece un tema muy interesante ya que angular utiliza esta librería en varios de sus métodos y se pueden realizar muchas operaciones complejas gracias a sus operadores.

**Comment by jdjuan** [comment]
Súper @camilo56  ! 😁 Éste es un tema muy necesario en Angular! 🅰️  Muchas gracias por proponerlo! 😁 

Te gustaría dar el tema a ti!? No olvides contarnos quién eres y dar una descripción de la charla! 🎉 
**[Speaker Guidelines](https://github.com/angular-medellin/meetup/blob/master/assets/SPEAKERS.md#-speakers-)**

**Comment by camilo56** [comment]
Hola @jdjuan Mi nombre es cristian camilo colorado soy desarrollador front end, he estado trabajando con rxjs y me parece un tema un importante, me gustaría contarle a la comunidad que es rxjs, como se utiliza, sus ventajas y mostrarles algunos de los operadores que nos pueden ayudar mucho.

**Comment by jdjuan** [comment]
Excelente presentación @camilo56 🥇
