### ISSUE TITLE
JetBrains puede hacer aportes a la comunidad...

### ISSUE THREAD

**Issue by gabrielizalo** [angular-medellin/meetup#77]
# Me gustaría...

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [X] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [ ] 🤡 Otro

## Descripción
[JetBrains](https://www.jetbrains.com/), compañía desarrolladora de IDEs (como [IntelliJ IDEA](https://www.jetbrains.com/idea/) y [WebStorm](https://www.jetbrains.com/webstorm/), apoyan comunidades como esta. 
Podemos conseguir que nos regalen 2 o 3 Licencias de sus productos para rifar en cada Meetup. 
Yo las conseguí para el Meetup de Todo1. Ellos piden a cambio que los coloquemos como parte de los patrocinadores (incluir el logo) y que tengamos un email del meetup, algo como meetup@angularmedellin.com, que es donde enviarían mensualmente las licencias.

También están abiertos a ser patrocinadores de eventos. Podemos invitarlos a que sean patrocinadores del **NG Colombia**... Que tal que venga uno de esos duros y den una charla de "_Cómo potenciar el desarrollo con Angular usando WebStorm_" o que sea una charla en línea como la del sábado.

**Importante:** Yo no tengo ninguna afiliación con JetBrains. Eso si, soy un usuario apasionado de sus IDEs.  :nerd_face:

**Comment by alejandro-rios** [comment]
Yo tambien uso sus IDE's, esta genial esa idea

**Comment by danielcb29** [comment]
Que buena idea! , GitHub no hace lo mismo? sería genial que rifaran paquetes completos de GitHub o ellos
 pudieran dar una charla en el NgColombia 😄

**Comment by pablovem** [comment]
Complementando la propuesta de @danielcb29, aqui esta la info para Github: https://community.github.com/

**Comment by jdjuan** [comment]
Está genial la idea @gabrielizalo ! 🥇  Me parece muy adecuado invitar a estos sponsors que nos pueden dar una mano con la comunidad! 😁 

@gabrielizalo ¿Cuál es el paso a seguir? ¿Cómo los podemos contactar? ¿Podemos hablar por Gitter?

@pablovem ! Gracias por el dato de GitHub, no tenía ni idea!, es una lástima que no podamos aprovecharlo este año pero para el 2018 será una realidad! 🤙

**Comment by gabrielizalo** [comment]
@jdjuan Claro.. Soy nuevo en Gitter... ¿Eso tiene mensajes directos o te hablo por un canal especial?
Recuerda que necesitan la cuenta meetup@angularmedellin.com (es un ejemplo. la idea es que no sea una cuenta a nombre de una persona).

**Comment by danielcb29** [comment]
@gabrielizalo Gabriel como vas? , me podes escribir por Gitter para ver como procedemos con las licencias de JetBrains? Hablemos y miremos que debemos hacer para que sea una realidad 😄 . Estoy como @danielcb29
