### ISSUE TITLE
Participar en el Blog

### ISSUE THREAD

**Issue by robinHurtado** [angular-medellin/meetup#78]
# Me gustaría...
Participar en el Blog

- [ ] 😎 Ser el próximo speaker
- [ ] 😃 Proponer un tema 
- [ ] 😋 Sugerir una idea/proyecto
- [ ] 🤠 Convertirme en organizador
- [ ] 🤕 Resolver una duda técnica
- [x ] 🤡 Otro

## Descripción
 What's your article about?
A brief and general introduction for a newbie in Angular.

Who you are: Mentioning your context/experience is key for us to understand why you are eligible to write about the particular topic.
I am a passionate full stack developer, i am working remotely at toptive.co. I have more than two years of expereince developing web sites.
i have worked with technologies such as : ColdFusion, Nodejs, DHTMLX, Angular1, ReactJs, React Native, JQuery.

Do you feel confident about writing in english? Do you already have an estimation about your article extension?
Yes, i feel confident and i have the article already, at what email do i need to send it?

**Comment by pablovem** [comment]
Great to read this @robinHurtado, let's discuss this on gitter. Please send me a private message with the article url. 

Regards

**Comment by robinHurtado** [comment]
Hi, i mean i got the article writtten in Word, can i send it to your email? besides what is the url for the gitter page?

**Comment by pablovem** [comment]
I see, let's use [Gitter](https://gitter.im/angular-medellin/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to discuss the details of how to upload it to Medium. Deal?

**Comment by jdjuan** [comment]
Wujuuu, first article from the community members! 👆👆👆

**Comment by pablovem** [comment]
The article [Why am I starting loving Angular?](https://medium.com/angularmedellin/are-you-a-newbie-on-angular-772926610596) has been published.
