### ISSUE TITLE
I just wrote a blog post 'Lazy loading Angular Modules'

### ISSUE THREAD

**Issue by camilogiraldo** [angular-medellin/meetup#83]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ ] 😁 Participar de los Angular Labs
* [x] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Hello guys, I'm Juan Camilo Giraldo Software engineer at Sura.  
I've been in love with Angular and javascript related frameworks in general as long as 2 years now. I really enjoy learning new things and this time I just wanna get started in blogging and share some knowledge with our community.

I want to share a blog post about Angular Lazy Loading modules, that you can find here: 
https://medium.com/@camilogiraldo91/lazy-loading-angular-modules-58fc844b5c7d and is open to your feedback as long we all are learning new things every second.
👍  Thank you guys, feel free to share any questions or comments.

🎉 🎉 🎉

**Comment by jdjuan** [comment]
Camilo this is awesome! ⭐️ 
Congratulations on this Angular post! Which seems to be your first on Medium! 👍 
I will ask your post to be featured at our next meetup this Saturday so more people can learn about Routes! 👌 

By the way, Angular Medellín's medium we are looking forward to inviting people to write. We'd love if you replicated your post there so you could reach more people without losing your authorship! 
If you are in, @pablovem can guide you through it 🏅

**Comment by camilogiraldo** [comment]
Let's do it :sunglasses:

**Comment by pablovem** [comment]
Good afternoon @camilogiraldo, very nice post! 🎉 

Could you please chose to receive emails over Medium? this to allow the request by the publication. We can discuss it over slack if you want.

Thanks in advance

**Comment by camilogiraldo** [comment]
I just did it, can we try now? @pablovem

**Comment by pablovem** [comment]
Thanks a lot, the request has been already submitted. 😄  

Please let me know if you received the message.

**Comment by camilogiraldo** [comment]
Done ! I've received the message, just accepted publication request.

**Comment by pablovem** [comment]
Thanks @camilogiraldo! your article [Lazy loading Angular Modules](https://medium.com/angularmedellin/lazy-loading-angular-modules-58fc844b5c7d) has been published.
