### ISSUE TITLE
Quiero participar en un labs

### ISSUE THREAD

**Issue by lliccien** [angular-medellin/meetup#85]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Soy Ludwring Liccien desarrollador web php con más de 15 años de experiencia
Quiero participar en los labs por que me gusta mucho angular he realizado varios cursos en platzi.com y udemy.com y quiero aprender más
A la fecha de hoy laboralmente hablando tengo 15 días programando en angular es mi primera experiencia laboral con frontend y para hacerlo más fácil me toco comenzar con redux en angular.

Gracias de antemano y los felicito por eta gran iniciativa

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @lliccien! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
