### ISSUE TITLE
Me gustaría participar de los Angular labs.

### ISSUE THREAD

**Issue by EsneiderSM** [angular-medellin/meetup#86]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción

Hola, Mi nombre es Esneider Serna M. Soy desarrollador y en el último año he tenido la oportunidad de trabajar en algunos proyectos con Angular. Quisiera participar de los Angular Labs ya que me gusta mucho trabajar con Angular y creo que estos espacios son excelentes para tener la oportunidad de seguir aprendiendo cada vez más de cada uno de los integrantes de la comunidad.

Saludos y muchas gracias!

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @EsneiderSM! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
