### ISSUE TITLE
Participar en un lab

### ISSUE THREAD

**Issue by dannybotello12** [angular-medellin/meetup#87]
Me gustaría... 

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

Soy Danny Ricardo Botello Desarrollador nuevo en Angular llevo 4 meses codificando y aprendiendo

**Comment by pablovem** [comment]
¡ @dannybotello12  !

¡Queremos agradecerte por participar de los Angular Labs! 👍 Lamentamos decirte que no ha sido seleccionado en esta ocasión 😢. La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

¡Pero eso no importa! Porque tenemos un premio para ti por haber aplicado. 
!Ven a nuestro próximo meetup y búscanos para entregártelo! 🎉
