### ISSUE TITLE
Labs

### ISSUE THREAD

**Issue by rojasjuniore** [angular-medellin/meetup#88]
* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [🌟] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

😃 Quién eres: Junior Rojas (rojasjuniore)
😁 Por qué quieres participar de los Angular Labs: Porque seria genial aprender de los mejores y seguir profundizando mis conocimientos. 
🤓 Cuánto tiempo llevas codificando en Angular: 6+ meses

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @rojasjuniore! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*

**Comment by rojasjuniore** [comment]
![2014-10-22 11_35_09](https://thumbs.gfycat.com/SingleWellgroomedCreature-max-1mb.gif)
