### ISSUE TITLE
Angular Lab Application

### ISSUE THREAD

**Issue by edarioq** [angular-medellin/meetup#89]
* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

Quién eres
 - Edgar Quintero (Frontend Engineer)

Por qué quieres participar de los Angular Labs
 - Improve my Angular ninja skills and meet cool/interesting people!

Cuánto tiempo llevas codificando en Angular
 - 6 months give or take

**Comment by pablovem** [comment]
! @edarioq !

¡Queremos agradecerte por participar de los Angular Labs! 👍 Lamentamos decirte que no ha sido seleccionado en esta ocasión 😢. La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

¡Pero eso no importa! Porque tenemos un premio para ti por haber aplicado. 
!Ven a nuestro próximo meetup y búscanos para entregártelo! 🎉
