### ISSUE TITLE
Participación en el lab

### ISSUE THREAD

**Issue by anibalortegap** [angular-medellin/meetup#90]
* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x ] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Hola soy Anibal Ortega me gustaría participar en el labs de angular, llevó 6 meses trabajando poco a poco con angular, me gustaría ampliar mis conocimientos con este labs y contribuir más a la comunidad.

Saludos

**Comment by pablovem** [comment]
¡ @anibalortegap  !

¡Queremos agradecerte por participar de los Angular Labs! 👍 Lamentamos decirte que no ha sido seleccionado en esta ocasión 😢. La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

¡Pero eso no importa! Porque tenemos un premio para ti por haber aplicado. 
!Ven a nuestro próximo meetup y búscanos para entregártelo! 🎉
