### ISSUE TITLE
Quiero participar en el Angular Lab #1

### ISSUE THREAD

**Issue by gabrielizalo** [angular-medellin/meetup#91]
# Me gustaría...
* [X] 😁 Participar de los Angular Labs

## Descripción
😃 **Quién eres:** Gabriel Porras - Desarrollador Web 
😁 **¿Por qué quieres participar de los Angular Labs?:** Quiero aprender realmente Angular. He hecho cosas muy básicas y aún me encuentro perdido en este super mundo.
:dizzy_face: **¿Cuánto tiempo llevas codificando en Angular?:** "3 meses".

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @gabrielizalo! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
