### ISSUE TITLE
Participacion en el Angular labs

### ISSUE THREAD

**Issue by erifranck** [angular-medellin/meetup#92]
# Me gustaría...

* [] 😎 Ser el próximo speaker
* [] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [] 😊 Escribir un artículo en el Blog
* [] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Soy Erifranck Nuñez Desarrollador frontend Amante a Javascript tengo 3 años de experiencia como programador, me encantaria participar en el angular labs porque me gusta poner a prueba mis habilidades y los Stikers :smile: codeando con angular llevo como año y medio no poseo proyecto formal con este framework pero me gusta practicarlo

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @erifranck! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
