### ISSUE TITLE
Angular Labs -> Alejandra Giraldo

### ISSUE THREAD

**Issue by maleja111** [angular-medellin/meetup#94]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [X] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
smiley Quién eres: Soy Alejandra Giraldo, soy desarrolladora Front-end.
grin Por qué quieres participar de los Angular Labs: Soy desarrolladora desde hace unos 6 años,
pero desde hace menos de un año, estoy en el proceso de aprendizaje en angular, la curva de aprendizaje que he tenido en estos pocos meses me ha permitido tocar temas como forms, reactive forms, service, pero me gustaria aprender muchisimo mas!

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @maleja111! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
