### ISSUE TITLE
Angular Labs -> Lina Montaño 🤓

### ISSUE THREAD

**Issue by calypsobronte** [angular-medellin/meetup#95]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción

:smiley: Quién eres : soy Lina Montaño en redes sociales me encuentran como @calypso_bronte, estudiante en formación de Desarrollo de Software. Pertenezco a @pionerasdev comunidad enfocada a empoderar a chicas a unirse a el mundo mágico de la programación. 
:grimacing:  Por qué quieres participar de los Angular Labs: Obtener un amplio conocimiento de esta herramienta que facilita la vida del programador que se va enfocando para la parte FrontEnd y alli ***no morir en el intento*** y sera una forma de aprender al lado de un guia y después poder replicar este conocimiento a mi comunidad y así atreverme a dar una charla en algo que aprendi.
:nerd_face: Cuánto tiempo llevas codificando en Angular: no este no he codificado solo he leído, visto vídeos y he escuchado hablar de lo maravilloso que es programar con angular; esta seria una brillante oportunidad de poder codificar y hablar el mismo lenguaje que muchos programan. :call_me_hand:

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @calypsobronte ! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
