### ISSUE TITLE
Angular Labs Frank Betancur

### ISSUE THREAD

**Issue by Krank2me** [angular-medellin/meetup#96]
# quien soy:
Me llamo Frank Betancur, Ingeniero de sistemas con experiencia en Java y últimamente gomoso con JS y todos sus sabores, especialmente en Angular 

# quiero participar del Lab por que:
quiero participar por que quiero seguir aprendiendo y aumentar mi skill en este framework

# cuanto llevo codificando en Angular:
llevo mas o menos 3 meses estudiando y codificando en angular

# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @Krank2me! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
