### ISSUE TITLE
Angular Labs

### ISSUE THREAD

**Issue by rhoyos1985** [angular-medellin/meetup#97]
Me gustaría participar de los Angular Labs para adquirir mayor conocimiento sobre angular y sus herramientas

Trabaje con Angular 1 y 2 alrededor de 1 año

* [ x] 😎 Ser el próximo speaker
* [ x] 🤠 Publicar mi solución al Angular Challenge
* [x ] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Me llamo Richard Hoyos
Soy frontend developer

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @rhoyos1985! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*

**Comment by rhoyos1985** [comment]
Hola 

Gracias por tener en cuenta, estoy ansioso de empesar
