### ISSUE TITLE
Carlos Mario Villadiego - Angular Lab

### ISSUE THREAD

**Issue by carvarr** [angular-medellin/meetup#98]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
Hola me gustaría estar en el lab para aprender nuevas capacidades y participar en la comunidad, he trabajado por 2 años en angularjs (la primera version) y 1 año con angular 2+. Es la primera vez que estaría en el lab y espero la oportunidad para conocer la comunidad de este lenguaje. Saludos a tod@s

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @carvarr! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
