### ISSUE TITLE
Angular Labs

### ISSUE THREAD

**Issue by JamesChe91** [angular-medellin/meetup#99]
# Me gustaría...

* [ ] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [x] 😁 Participar de los Angular Labs
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

Mi nombre es James, soy desarrollador web, quiero estar en el lab para afianzar mis conocimientos en Angular. Llevo programando en Angular desde que comenzaron los meetups de la comunidad.

**Comment by pablovem** [comment]
🎉 ¡Felicitaciones @JamesChe91! 🎉
¡Te hemos seleccionado para participar del Angular Lab!

La comunidad mostró interés en esta actividad y debimos evaluar uno a uno los perfiles basados en los [Criterios de Selección](https://github.com/angular-medellin/meetup/tree/master/assets/3.%20labs).

Si no lo has hecho entra ahora mismo al [Slack](https://join.slack.com/t/ng-colombia/shared_invite/enQtMjgwMjc3ODk1NjMyLTBjMmE4YmQzYTA0ZGNjNTVhMmNlMmQ1YWRjNGFlOWE4MDBjMWM3M2UwNmFjZWFhNmZkYzVmNDc3ZWQ5MmQwZmY) para conocer el resto de condiciones. *Esperamos contar contigo este sábado*
